# Generated by Django 5.1.15 on 2026-08-11 15:21

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('full_code', models.CharField(help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA-[A-Z]{2,4}-[A-Z]{2,4}(-[A-Z0-9]{2,6})?-\\d{3}$')], verbose_name='Full Code')),
                ('short_alias', models.CharField(blank=True, help_text='Kısa kullanım kodu (örn. QA-FRM-012).', max_length=40, verbose_name='Short / Alias')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('type', models.CharField(choices=[('POL', 'Policy (L1)'), ('MAN', 'Manual (L1)'), ('CDD', 'Corporate Design Doc (L1)'), ('NAV', 'Navigation Map (L1)'), ('PRO', 'Procedure (L2)'), ('SOP', 'SOP / Work Instruction (L3)'), ('WI', 'Work Instruction (L3)'), ('CHK', 'Checklist (L4)'), ('FRM', 'Form (L4)'), ('REG', 'Register (L4)'), ('LOG', 'Log (L4)'), ('RPT', 'Report (L4)'), ('MST', 'Master Data (L5)'), ('SPC', 'Specification (L5)'), ('PLN', 'Plan (L2)'), ('SCH', 'Schedule (L2)'), ('SET', 'Package/Set (L1)')], max_length=4, verbose_name='Tip')),
                ('level', models.CharField(choices=[('L1', 'L1 Corporate direction'), ('L2', 'L2 Common control'), ('L3', 'L3 Execution'), ('L4', 'L4 Evidence'), ('L5', 'L5 Master data')], max_length=2, verbose_name='Seviye')),
                ('function', models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier')], max_length=4, verbose_name='Fonksiyon')),
                ('source_procedure', models.CharField(blank=True, help_text='Örn. MAPA-IMS-PRO-DOC', max_length=200, verbose_name='Kaynak prosedür(ler)')),
                ('owner_role', models.CharField(help_text='Group.name veya serbest metin (geçiş dönemi).', max_length=100, verbose_name='Sahip rol')),
                ('package_wave', models.CharField(blank=True, help_text='Örn. "Operational Packages 004-009"', max_length=100, verbose_name='Paket dalgası')),
                ('status', models.CharField(choices=[('AR', 'Architecture Review (placeholder)'), ('DR', 'Draft'), ('IS', 'Controlled Issue'), ('AC', 'Activated (live)'), ('RT', 'Retired')], default='DR', max_length=2, verbose_name='Durum')),
                ('revision', models.CharField(default='R0', max_length=8, verbose_name='Revizyon')),
                ('activation_gate', models.TextField(help_text='Aktivasyon için gereken kabul kriterleri (SOP+eğitim+bir kabul edilmiş kayıt).', verbose_name='Aktivasyon kapısı')),
                ('objective_evidence_rule', models.TextField(help_text='Boş şablon evidence değildir; ne kabul edilir?', verbose_name='Objektif kanıt kuralı')),
                ('trigger_type', models.CharField(choices=[('EVENT', 'Olay / değişiklik / karar tetiklemeli'), ('ROUTINE', 'Rutin / işlem / vardiya bazlı'), ('REGISTER', 'Register / master (periyodik review)'), ('OTHER', 'Diğer')], default='OTHER', max_length=10, verbose_name='Tetik tipi')),
                ('primary_preparer_role', models.CharField(blank=True, max_length=100, verbose_name='Ana hazırlayan rol')),
                ('review_approval_model', models.TextField(blank=True, help_text='Hazırlayan / bağımsız reviewer / QA-HSE-IT / karar yetkisi zinciri.', verbose_name='Review + onay modeli')),
                ('example_record_id_pattern', models.CharField(blank=True, help_text='Örn. QA-FRM012-2026-0001 veya PRD-BMR-2026-0001', max_length=100, verbose_name='Örnek Record ID formatı')),
                ('archive_path_pattern', models.CharField(blank=True, help_text='Örn. /MCOS/IMS/RECORDS/QA/<YYYY>/<Code>/<Record-ID>/', max_length=200, verbose_name='Arşiv yolu formatı')),
                ('retention_authority', models.CharField(blank=True, help_text='Örn. MAPA-IMS-MST-REC-001; yasal/sözleşme uzun süre öncelikli', max_length=200, verbose_name='Retention makamı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('business_lines', models.ManyToManyField(blank=True, related_name='controlled_codes', to='businessline.businessline', verbose_name='Uygulanabilir iş kolları (boş = tümü/kurumsal)')),
            ],
            options={
                'verbose_name': 'Kontrollü Kod',
                'verbose_name_plural': 'Kontrollü Kodlar (Register)',
                'ordering': ['function', 'type', 'full_code'],
            },
        ),
        migrations.CreateModel(
            name='ControlledCodeRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('revision', models.CharField(max_length=8, verbose_name='Revizyon')),
                ('revision_date', models.DateField(verbose_name='Revizyon tarihi')),
                ('change_summary', models.TextField(verbose_name='Değişiklik özeti')),
                ('reviewed_by', models.CharField(blank=True, max_length=200, verbose_name='İnceleyen')),
                ('approved_by', models.CharField(blank=True, max_length=200, verbose_name='Onaylayan')),
                ('issue_state', models.CharField(choices=[('IDR', 'Internal draft'), ('PIR', 'Pre-issue review'), ('CI', 'Controlled Issue'), ('AC', 'Activated (live)'), ('SUP', 'Superseded')], default='IDR', max_length=3, verbose_name='Yayın durumu')),
                ('authority_record', models.CharField(blank=True, help_text='Örn. CN-2026-0001 (Change Notice)', max_length=100, verbose_name='Yetki kaydı')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='registry.controlledcode', verbose_name='Kontrollü Kod')),
            ],
            options={
                'verbose_name': 'Kod Revizyonu',
                'verbose_name_plural': 'Kod Revizyonları',
                'ordering': ['code', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalControlledCode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('full_code', models.CharField(db_index=True, help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA-[A-Z]{2,4}-[A-Z]{2,4}(-[A-Z0-9]{2,6})?-\\d{3}$')], verbose_name='Full Code')),
                ('short_alias', models.CharField(blank=True, help_text='Kısa kullanım kodu (örn. QA-FRM-012).', max_length=40, verbose_name='Short / Alias')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('type', models.CharField(choices=[('POL', 'Policy (L1)'), ('MAN', 'Manual (L1)'), ('CDD', 'Corporate Design Doc (L1)'), ('NAV', 'Navigation Map (L1)'), ('PRO', 'Procedure (L2)'), ('SOP', 'SOP / Work Instruction (L3)'), ('WI', 'Work Instruction (L3)'), ('CHK', 'Checklist (L4)'), ('FRM', 'Form (L4)'), ('REG', 'Register (L4)'), ('LOG', 'Log (L4)'), ('RPT', 'Report (L4)'), ('MST', 'Master Data (L5)'), ('SPC', 'Specification (L5)'), ('PLN', 'Plan (L2)'), ('SCH', 'Schedule (L2)'), ('SET', 'Package/Set (L1)')], max_length=4, verbose_name='Tip')),
                ('level', models.CharField(choices=[('L1', 'L1 Corporate direction'), ('L2', 'L2 Common control'), ('L3', 'L3 Execution'), ('L4', 'L4 Evidence'), ('L5', 'L5 Master data')], max_length=2, verbose_name='Seviye')),
                ('function', models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier')], max_length=4, verbose_name='Fonksiyon')),
                ('source_procedure', models.CharField(blank=True, help_text='Örn. MAPA-IMS-PRO-DOC', max_length=200, verbose_name='Kaynak prosedür(ler)')),
                ('owner_role', models.CharField(help_text='Group.name veya serbest metin (geçiş dönemi).', max_length=100, verbose_name='Sahip rol')),
                ('package_wave', models.CharField(blank=True, help_text='Örn. "Operational Packages 004-009"', max_length=100, verbose_name='Paket dalgası')),
                ('status', models.CharField(choices=[('AR', 'Architecture Review (placeholder)'), ('DR', 'Draft'), ('IS', 'Controlled Issue'), ('AC', 'Activated (live)'), ('RT', 'Retired')], default='DR', max_length=2, verbose_name='Durum')),
                ('revision', models.CharField(default='R0', max_length=8, verbose_name='Revizyon')),
                ('activation_gate', models.TextField(help_text='Aktivasyon için gereken kabul kriterleri (SOP+eğitim+bir kabul edilmiş kayıt).', verbose_name='Aktivasyon kapısı')),
                ('objective_evidence_rule', models.TextField(help_text='Boş şablon evidence değildir; ne kabul edilir?', verbose_name='Objektif kanıt kuralı')),
                ('trigger_type', models.CharField(choices=[('EVENT', 'Olay / değişiklik / karar tetiklemeli'), ('ROUTINE', 'Rutin / işlem / vardiya bazlı'), ('REGISTER', 'Register / master (periyodik review)'), ('OTHER', 'Diğer')], default='OTHER', max_length=10, verbose_name='Tetik tipi')),
                ('primary_preparer_role', models.CharField(blank=True, max_length=100, verbose_name='Ana hazırlayan rol')),
                ('review_approval_model', models.TextField(blank=True, help_text='Hazırlayan / bağımsız reviewer / QA-HSE-IT / karar yetkisi zinciri.', verbose_name='Review + onay modeli')),
                ('example_record_id_pattern', models.CharField(blank=True, help_text='Örn. QA-FRM012-2026-0001 veya PRD-BMR-2026-0001', max_length=100, verbose_name='Örnek Record ID formatı')),
                ('archive_path_pattern', models.CharField(blank=True, help_text='Örn. /MCOS/IMS/RECORDS/QA/<YYYY>/<Code>/<Record-ID>/', max_length=200, verbose_name='Arşiv yolu formatı')),
                ('retention_authority', models.CharField(blank=True, help_text='Örn. MAPA-IMS-MST-REC-001; yasal/sözleşme uzun süre öncelikli', max_length=200, verbose_name='Retention makamı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Kontrollü Kod',
                'verbose_name_plural': 'historical Kontrollü Kodlar (Register)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='controlledcode',
            index=models.Index(fields=['function', 'type'], name='registry_co_functio_fc415c_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledcode',
            index=models.Index(fields=['level'], name='registry_co_level_db8861_idx'),
        ),
        migrations.AddIndex(
            model_name='controlledcode',
            index=models.Index(fields=['status'], name='registry_co_status_02d94a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlledcoderevision',
            unique_together={('code', 'revision')},
        ),
    ]
