# Generated by Django 5.1.15 on 2026-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledcode',
            name='function',
            field=models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier'), ('WHS', "Warehouse alt-fonksiyon (WHL'nin eski adı)"), ('ENV', 'Environment (HSE alt-fonksiyon)'), ('MET', 'Metrology (MNT alt-fonksiyon)'), ('DPO', 'Data Protection Officer'), ('LEG', 'Legal'), ('FIN', 'Finance')], max_length=4, verbose_name='Fonksiyon'),
        ),
        migrations.AlterField(
            model_name='historicalcontrolledcode',
            name='function',
            field=models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier'), ('WHS', "Warehouse alt-fonksiyon (WHL'nin eski adı)"), ('ENV', 'Environment (HSE alt-fonksiyon)'), ('MET', 'Metrology (MNT alt-fonksiyon)'), ('DPO', 'Data Protection Officer'), ('LEG', 'Legal'), ('FIN', 'Finance')], max_length=4, verbose_name='Fonksiyon'),
        ),
    ]
