# Generated by Django 5.1.15 on 2026-08-11 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_controlledcode_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledcode',
            name='full_code',
            field=models.CharField(help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA-[A-Z]{2,5}-[A-Z]{2,4}(-[A-Z0-9]{2,6})?-\\d{3}$')], verbose_name='Full Code'),
        ),
        migrations.AlterField(
            model_name='controlledcode',
            name='function',
            field=models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier'), ('WHS', "Warehouse alt-fonksiyon (WHL'nin eski adı)"), ('ENV', 'Environment (HSE alt-fonksiyon)'), ('MET', 'Metrology (MNT alt-fonksiyon)'), ('DPO', 'Data Protection Officer'), ('LEG', 'Legal'), ('FIN', 'Finance'), ('SAL', 'Sales'), ('CPL', 'Compliance'), ('ORG', 'Organization'), ('CUS', 'Customer'), ('RDI', 'R&D / Innovation'), ('RCV', 'Receiving'), ('TRA', 'Training'), ('SST', 'Site Safety / Security'), ('MFG', 'Manufacturing'), ('LAB', 'Laboratory'), ('MKT', 'Marketing'), ('COMMS', 'Communications')], max_length=5, verbose_name='Fonksiyon'),
        ),
        migrations.AlterField(
            model_name='historicalcontrolledcode',
            name='full_code',
            field=models.CharField(db_index=True, help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA-[A-Z]{2,5}-[A-Z]{2,4}(-[A-Z0-9]{2,6})?-\\d{3}$')], verbose_name='Full Code'),
        ),
        migrations.AlterField(
            model_name='historicalcontrolledcode',
            name='function',
            field=models.CharField(choices=[('COR', 'Corporate Governance'), ('OPS', 'Factory Operations'), ('QMS', 'QA / IMS'), ('QCL', 'QC & Laboratory'), ('RDT', 'R&D / Product / Formwork Technology'), ('PRD', 'Production'), ('SCM', 'Supply Chain & Purchasing'), ('WHL', 'Warehouse & Logistics'), ('MNT', 'Maintenance & Utilities'), ('HSE', 'Health, Safety & Environment'), ('COM', 'Commercial & Technical Service'), ('ADM', 'Finance / HR / Admin / IT Shared'), ('IMS', 'IMS (kurumsal)'), ('QA', 'QA (kurumsal alt-fonksiyon)'), ('IT', 'IT / OT'), ('HR', 'HR'), ('BCM', 'Business Continuity'), ('SUP', 'Supplier'), ('WHS', "Warehouse alt-fonksiyon (WHL'nin eski adı)"), ('ENV', 'Environment (HSE alt-fonksiyon)'), ('MET', 'Metrology (MNT alt-fonksiyon)'), ('DPO', 'Data Protection Officer'), ('LEG', 'Legal'), ('FIN', 'Finance'), ('SAL', 'Sales'), ('CPL', 'Compliance'), ('ORG', 'Organization'), ('CUS', 'Customer'), ('RDI', 'R&D / Innovation'), ('RCV', 'Receiving'), ('TRA', 'Training'), ('SST', 'Site Safety / Security'), ('MFG', 'Manufacturing'), ('LAB', 'Laboratory'), ('MKT', 'Marketing'), ('COMMS', 'Communications')], max_length=5, verbose_name='Fonksiyon'),
        ),
    ]
