# Generated by Django 5.1.15 on 2026-08-11 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_controlledcode_full_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledcode',
            name='full_code',
            field=models.CharField(help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA(-[A-Z][A-Z0-9]{1,5}){1,3}-\\d{3}$')], verbose_name='Full Code'),
        ),
        migrations.AlterField(
            model_name='historicalcontrolledcode',
            name='full_code',
            field=models.CharField(db_index=True, help_text='MAPA-<Function>-<Type>-<Subject?>-<Seq>', max_length=60, validators=[django.core.validators.RegexValidator(message='Format geçersiz. Beklenen: MAPA-<Function>-<Type>-<Subject?>-<Seq>. Örn: MAPA-IMS-FRM-NCR-001, MAPA-CDD-001, MAPA-IT-REG-004', regex='^MAPA(-[A-Z][A-Z0-9]{1,5}){1,3}-\\d{3}$')], verbose_name='Full Code'),
        ),
    ]
