# Generated by Django 5.1.15 on 2026-08-10 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('SUCCESS', 'Başarı'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('TASK', 'Görev (aksiyon gerektirir)')], default='INFO', max_length=8, verbose_name='Seviye')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Kullanıcıyı ilgili sayfaya götüren bağlantı.', max_length=255, verbose_name='Aksiyon URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma zamanı')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
