# Generated by Django 5.1.15 on 2026-08-10 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=80, verbose_name='Ad')),
                ('start_time', models.TimeField(verbose_name='Başlangıç saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş saati')),
                ('is_night', models.BooleanField(default=False, verbose_name='Gece vardiyası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('request_number', models.CharField(max_length=40, unique=True, verbose_name='Talep no')),
                ('type', models.CharField(choices=[('ANNUAL', 'Yıllık izin'), ('SICK', 'Hastalık'), ('UNPAID', 'Ücretsiz'), ('MATERNITY', 'Doğum'), ('BEREAVEMENT', 'Vefat'), ('OTHER', 'Diğer')], max_length=12, verbose_name='Tip')),
                ('start_date', models.DateField(verbose_name='Başlangıç')),
                ('end_date', models.DateField(verbose_name='Bitiş')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='Gün sayısı')),
                ('reason', models.TextField(blank=True, verbose_name='Gerekçe')),
                ('status', models.CharField(choices=[('REQUESTED', 'Talep edildi'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='REQUESTED', max_length=10, verbose_name='Durum')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ret gerekçesi')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('category', models.CharField(choices=[('HSE', 'İSG / Çevre'), ('QUALITY', 'Kalite'), ('TECHNICAL', 'Teknik'), ('REGULATORY', 'Mevzuat'), ('SOFT_SKILL', 'Kişisel gelişim'), ('ONBOARDING', 'Oryantasyon')], default='QUALITY', max_length=12, verbose_name='Kategori')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=5, verbose_name='Süre (saat)')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='Sağlayıcı')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Boşsa sınırsız.', null=True, verbose_name='Geçerlilik (gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('grants_competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granting_courses', to='iam.competency', verbose_name='Kazandırdığı yetkinlik')),
            ],
            options={
                'verbose_name': 'Eğitim Kursu',
                'verbose_name_plural': 'Eğitim Kursları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('session_number', models.CharField(max_length=40, unique=True, verbose_name='Etkinlik No')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Yer')),
                ('trainer', models.CharField(blank=True, max_length=200, verbose_name='Eğitmen')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('DELIVERED', 'Verildi'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=10, verbose_name='Durum')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='hr.trainingcourse', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Eğitim Etkinliği',
                'verbose_name_plural': 'Eğitim Etkinlikleri',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('role', models.CharField(blank=True, help_text='Operatör / kalite / lider / vb.', max_length=80, verbose_name='Görev')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planlandı'), ('COMPLETED', 'Yapıldı'), ('ABSENT', 'Devamsız'), ('SWAPPED', 'Değiştirildi')], default='SCHEDULED', max_length=10, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.shift', verbose_name='Vardiya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Vardiya Ataması',
                'verbose_name_plural': 'Vardiya Atamaları',
                'ordering': ['-date', 'shift'],
                'unique_together': {('user', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('result', models.CharField(choices=[('PASSED', 'Geçti'), ('FAILED', 'Kaldı'), ('ATTENDED', 'Katıldı (sınavsız)'), ('ABSENT', 'Katılmadı')], default='ATTENDED', max_length=8, verbose_name='Sonuç')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Puan')),
                ('certificate_number', models.CharField(blank=True, max_length=60, verbose_name='Sertifika no')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='training/%Y/', verbose_name='Sertifika PDF')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik sonu')),
                ('notes', models.TextField(blank=True, verbose_name='Not')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='hr.trainingsession', verbose_name='Etkinlik')),
            ],
            options={
                'verbose_name': 'Eğitim Kaydı',
                'verbose_name_plural': 'Eğitim Kayıtları',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
