# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('governance', '0001_initial'),
        ('qms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='qms.capa', verbose_name='Bağlı CAPA'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='ncr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings', to='qms.nonconformance', verbose_name='Açılan NCR'),
        ),
        migrations.AddField(
            model_name='historicalinternalaudit',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinternalaudit',
            name='lead_auditor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Baş denetçi'),
        ),
        migrations.AddField(
            model_name='historicalmanagementreview',
            name='chairperson',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Toplantı başkanı'),
        ),
        migrations.AddField(
            model_name='historicalmanagementreview',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalriskitem',
            name='capa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='qms.capa', verbose_name='Bağlı CAPA'),
        ),
        migrations.AddField(
            model_name='historicalriskitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalriskitem',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='auditors',
            field=models.ManyToManyField(blank=True, related_name='audits_as_auditor', to=settings.AUTH_USER_MODEL, verbose_name='Denetim ekibi'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='lead_auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_audits', to=settings.AUTH_USER_MODEL, verbose_name='Baş denetçi'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='governance.internalaudit', verbose_name='Denetim'),
        ),
        migrations.AddField(
            model_name='internalauditplan',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_audit_plans', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='governance.internalauditplan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='historicalinternalaudit',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='governance.internalauditplan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcılar'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='chairperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chaired_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Toplantı başkanı'),
        ),
        migrations.AddField(
            model_name='managementreviewaction',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_mr_actions', to=settings.AUTH_USER_MODEL, verbose_name='Atanan'),
        ),
        migrations.AddField(
            model_name='managementreviewaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='governance.managementreview', verbose_name='Toplantı'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='capa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='qms.capa', verbose_name='Bağlı CAPA'),
        ),
        migrations.AddField(
            model_name='riskitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu'),
        ),
    ]
