# Generated by Django 5.1.15 on 2026-08-11 03:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(choices=[('MCS', 'MAPA Concrete Solutions'), ('MPT', 'MAPA Precast Technologies'), ('MFT', 'MAPA Formwork Technologies'), ('MLTS', 'MAPA Laboratory & Technical Services')], max_length=8, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('operational_scope', models.TextField(help_text='NAV-001 §3 tanımına uygun kapsam metni.', verbose_name='Operasyonel kapsam')),
                ('typical_entry', models.CharField(blank=True, help_text='Örn. Production/batch event, Precast order/pour, Formwork job/fabrication, Contract/sample/method', max_length=200, verbose_name='Tipik giriş noktası')),
                ('qc_independence', models.TextField(blank=True, help_text='Üretimden bağımsız QC/Release yetkisi tanımı.', verbose_name='QC bağımsızlık kuralı')),
                ('release_authority', models.TextField(blank=True, help_text="Bu BL'de kim ne şartla release edebilir?", verbose_name='Serbest bırakma yetkisi')),
                ('external_certifications', models.TextField(blank=True, help_text='Örn. ISO 9001, ISO 14001, ISO 17025 (MLTS için).', verbose_name='Dış sertifikasyon/akreditasyon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'İş Kolu',
                'verbose_name_plural': 'İş Kolları',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBusinessLine',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('code', models.CharField(choices=[('MCS', 'MAPA Concrete Solutions'), ('MPT', 'MAPA Precast Technologies'), ('MFT', 'MAPA Formwork Technologies'), ('MLTS', 'MAPA Laboratory & Technical Services')], db_index=True, max_length=8, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('operational_scope', models.TextField(help_text='NAV-001 §3 tanımına uygun kapsam metni.', verbose_name='Operasyonel kapsam')),
                ('typical_entry', models.CharField(blank=True, help_text='Örn. Production/batch event, Precast order/pour, Formwork job/fabrication, Contract/sample/method', max_length=200, verbose_name='Tipik giriş noktası')),
                ('qc_independence', models.TextField(blank=True, help_text='Üretimden bağımsız QC/Release yetkisi tanımı.', verbose_name='QC bağımsızlık kuralı')),
                ('release_authority', models.TextField(blank=True, help_text="Bu BL'de kim ne şartla release edebilir?", verbose_name='Serbest bırakma yetkisi')),
                ('external_certifications', models.TextField(blank=True, help_text='Örn. ISO 9001, ISO 14001, ISO 17025 (MLTS için).', verbose_name='Dış sertifikasyon/akreditasyon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical İş Kolu',
                'verbose_name_plural': 'historical İş Kolları',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RoleBusinessLineScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('business_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_scopes', to='businessline.businessline', verbose_name='İş Kolu')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_line_scopes', to='auth.group', verbose_name='Rol (Group)')),
            ],
            options={
                'verbose_name': 'Rol × İş Kolu Yetki',
                'verbose_name_plural': 'Rol × İş Kolu Yetkileri',
                'unique_together': {('group', 'business_line')},
            },
        ),
    ]
