# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('valid_days', models.PositiveIntegerField(blank=True, help_text='Süreli yetkinlikler için (örn. iş güvenliği 365 gün)', null=True, verbose_name='Geçerlilik (gün)')),
            ],
            options={
                'verbose_name': 'Yetkinlik',
                'verbose_name_plural': 'Yetkinlikler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='iam.department', verbose_name='Üst departman')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('employee_no', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Sicil No')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Ünvan')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='İşe giriş')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='iam.department', verbose_name='Departman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
            },
        ),
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('object_id', models.PositiveBigIntegerField()),
                ('meaning', models.CharField(choices=[('APPROVED', 'Onaylandı'), ('REVIEWED', 'İncelendi'), ('RELEASED', 'Serbest bırakıldı'), ('REJECTED', 'Reddedildi'), ('WITNESSED', 'Şahit olarak imzalandı'), ('SIGNED_OFF', 'İmzalandı')], max_length=16, verbose_name='Anlam')),
                ('reason', models.CharField(help_text='Değişikliğin/kaydın gerekçesi (21 CFR 11 iz gerekliliği).', max_length=255, verbose_name='Gerekçe')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='İmza zamanı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='e_signatures', to=settings.AUTH_USER_MODEL, verbose_name='İmzalayan')),
            ],
            options={
                'verbose_name': 'E-imza',
                'verbose_name_plural': 'E-imzalar',
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='iam_esignat_content_7aa892_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('obtained_on', models.DateField(verbose_name='Alındığı tarih')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='Geçerlilik sonu')),
                ('evidence', models.CharField(blank=True, max_length=200, verbose_name='Kanıt (sertifika no vb.)')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='iam.competency', verbose_name='Yetkinlik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Yetkinliği',
                'verbose_name_plural': 'Kullanıcı Yetkinlikleri',
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
