# Generated by Django 5.1.15 on 2026-08-09 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='Sipariş No')),
                ('order_date', models.DateField(verbose_name='Sipariş tarihi')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Beklenen tarih')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('OPEN', 'Açık'), ('PARTIAL', 'Kısmi teslim'), ('RECEIVED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Satın Alma Siparişi',
                'verbose_name_plural': 'Satın Alma Siparişleri',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('receipt_number', models.CharField(max_length=40, unique=True, verbose_name='Kabul No')),
                ('received_date', models.DateField(verbose_name='Kabul tarihi')),
                ('receiver', models.CharField(blank=True, max_length=120, verbose_name='Teslim alan')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='masterdata.supplier', verbose_name='Tedarikçi')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='purchasing.purchaseorder', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Mal Kabul',
                'verbose_name_plural': 'Mal Kabuller',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Birim fiyat')),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Kabul edilen miktar')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='Sipariş')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'PO Satırı',
                'verbose_name_plural': 'PO Satırları',
                'unique_together': {('po', 'raw_material')},
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar')),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_line', to='inventory.rawmateriallot', verbose_name='Oluşturulan Lot')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt', verbose_name='Kabul')),
                ('po_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='purchasing.purchaseorderline', verbose_name='PO Satırı')),
            ],
            options={
                'verbose_name': 'Mal Kabul Satırı',
                'verbose_name_plural': 'Mal Kabul Satırları',
            },
        ),
    ]
