# Generated by Django 5.1.15 on 2026-08-10 06:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('period_start', models.DateField(verbose_name='Dönem başı')),
                ('period_end', models.DateField(verbose_name='Dönem sonu')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Beklenen miktar')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('80'), max_digits=5, verbose_name='Güven (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_forecasts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='masterdata.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Talep Tahmini',
                'verbose_name_plural': 'Talep Tahminleri',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='MRPRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('run_number', models.CharField(max_length=40, unique=True, verbose_name='Koşu no')),
                ('horizon_date', models.DateField(help_text='MRP bu tarihe kadar planlanmış üretim emirleri + siparişleri toplar.', verbose_name='Ufuk (bu tarihe kadar)')),
                ('include_forecasts', models.BooleanField(default=True, verbose_name='Talep tahminlerini dahil et')),
                ('include_open_sales_orders', models.BooleanField(default=True, verbose_name='Açık müşteri siparişleri')),
                ('include_planned_production_orders', models.BooleanField(default=True, verbose_name='Planlanmış üretim emirleri')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Çalıştırma zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_runs', to=settings.AUTH_USER_MODEL, verbose_name='Çalıştıran')),
            ],
            options={
                'verbose_name': 'MRP Koşusu',
                'verbose_name_plural': 'MRP Koşuları',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('requisition_number', models.CharField(max_length=40, unique=True, verbose_name='Talep no')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Miktar')),
                ('needed_by', models.DateField(blank=True, null=True, verbose_name='Gerekli olduğu tarih')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SUBMITTED', 'Sunuldu'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CONVERTED', "PO'ya dönüştürüldü"), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('justification', models.TextField(blank=True, verbose_name='Gerekçe')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden')),
                ('source_mrp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='mrp.mrprun', verbose_name='Kaynak MRP')),
            ],
            options={
                'verbose_name': 'Satın Alma Talebi',
                'verbose_name_plural': 'Satın Alma Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('gross_requirement', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Brüt ihtiyaç')),
                ('on_hand', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Mevcut stok (RELEASED lot)')),
                ('on_order', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Açık PO miktarı')),
                ('net_requirement', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='brüt - mevcut - açık PO', max_digits=14, verbose_name='Net ihtiyaç')),
                ('suggested_order_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Önerilen sipariş miktarı')),
                ('status', models.CharField(choices=[('OK', 'Yeterli'), ('SHORTAGE', 'Eksik'), ('REORDER', 'Reorder önerildi')], default='OK', max_length=10, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mrp.mrprun', verbose_name='MRP koşusu')),
            ],
            options={
                'verbose_name': 'Malzeme İhtiyacı',
                'verbose_name_plural': 'Malzeme İhtiyaçları',
                'ordering': ['-net_requirement'],
                'unique_together': {('run', 'raw_material')},
            },
        ),
    ]
