# Generated by Django 5.1.15 on 2026-08-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('lot_number', models.CharField(max_length=60, unique=True, verbose_name='Lot No')),
                ('received_date', models.DateField(verbose_name='Kabul tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son kullanma')),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kabul miktarı')),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kalan miktar')),
                ('qc_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RELEASED', 'Serbest'), ('QUARANTINE', 'Karantina'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16, verbose_name='Kalite durumu')),
                ('coa_reference', models.CharField(blank=True, max_length=120, verbose_name='COA referansı')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='masterdata.container', verbose_name='Kap')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='masterdata.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Hammadde Lotu',
                'verbose_name_plural': 'Hammadde Lotları',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Kabul'), ('CONSUMPTION', 'Tüketim'), ('ADJUSTMENT', 'Düzeltme')], max_length=16, verbose_name='Hareket tipi')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar (+/−)')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='Referans')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman damgası')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.rawmateriallot', verbose_name='Lot')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-timestamp'],
            },
        ),
    ]
