# Generated by Django 5.1.15 on 2026-08-09 19:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmateriallot',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Kabul anındaki birim fiyat (PO'dan kopyalanır).", max_digits=12, verbose_name='Birim maliyet'),
        ),
    ]
