# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmateriallot_unit_cost'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRawMaterialLot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('lot_number', models.CharField(db_index=True, max_length=60, verbose_name='Lot No')),
                ('received_date', models.DateField(verbose_name='Kabul tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son kullanma')),
                ('received_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kabul miktarı')),
                ('remaining_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kalan miktar')),
                ('qc_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RELEASED', 'Serbest'), ('QUARANTINE', 'Karantina'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16, verbose_name='Kalite durumu')),
                ('coa_reference', models.CharField(blank=True, max_length=120, verbose_name='COA referansı')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Kabul anındaki birim fiyat (PO'dan kopyalanır).", max_digits=12, verbose_name='Birim maliyet')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('container', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.container', verbose_name='Kap')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'historical Hammadde Lotu',
                'verbose_name_plural': 'historical Hammadde Lotları',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
