# Generated by Django 5.1.15 on 2026-08-21 08:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalrawmateriallot_business_line_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('adjustment_number', models.CharField(db_index=True, max_length=40, verbose_name='Ajustement No')),
                ('adjustment_type', models.CharField(choices=[('INVENTORY', 'Envanter sayımı (Inventaire)'), ('LOSS', 'Kayıp / Fire (Perte)'), ('DAMAGE', 'Hasar (Dégât)'), ('RETURN', 'Tedarikçiye iade'), ('CORRECTION', 'Düzeltme (Correction)'), ('OTHER', 'Diğer')], max_length=16, verbose_name="Type d'ajustement")),
                ('reason', models.TextField(help_text='Düzeltme sebebi — envanter farkı, döküntü, kırılma vs.', verbose_name='Motif')),
                ('qty_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté avant')),
                ('qty_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté après')),
                ('delta', models.DecimalField(decimal_places=4, help_text='Qté après − Qté avant (otomatik hesaplanır).', max_digits=12, verbose_name='Delta')),
                ('document_type', models.CharField(blank=True, help_text='Örn. Rapor No, Envanter listesi, İç yazışma.', max_length=80, verbose_name='Document type')),
                ('document_ref', models.CharField(blank=True, max_length=120, verbose_name='Document référence')),
                ('document', models.TextField(blank=True, help_text='Perte / Dégât / Retour için zorunlu.', max_length=100, null=True, verbose_name='Document justificatif')),
                ('performed_at', models.DateTimeField(verbose_name='Zaman')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('movement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.stockmovement', verbose_name='Stok hareketi')),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yapan')),
            ],
            options={
                'verbose_name': 'historical Ajustement de stock',
                'verbose_name_plural': 'historical Ajustements de stock',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('adjustment_number', models.CharField(max_length=40, unique=True, verbose_name='Ajustement No')),
                ('adjustment_type', models.CharField(choices=[('INVENTORY', 'Envanter sayımı (Inventaire)'), ('LOSS', 'Kayıp / Fire (Perte)'), ('DAMAGE', 'Hasar (Dégât)'), ('RETURN', 'Tedarikçiye iade'), ('CORRECTION', 'Düzeltme (Correction)'), ('OTHER', 'Diğer')], max_length=16, verbose_name="Type d'ajustement")),
                ('reason', models.TextField(help_text='Düzeltme sebebi — envanter farkı, döküntü, kırılma vs.', verbose_name='Motif')),
                ('qty_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté avant')),
                ('qty_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté après')),
                ('delta', models.DecimalField(decimal_places=4, help_text='Qté après − Qté avant (otomatik hesaplanır).', max_digits=12, verbose_name='Delta')),
                ('document_type', models.CharField(blank=True, help_text='Örn. Rapor No, Envanter listesi, İç yazışma.', max_length=80, verbose_name='Document type')),
                ('document_ref', models.CharField(blank=True, max_length=120, verbose_name='Document référence')),
                ('document', models.FileField(blank=True, help_text='Perte / Dégât / Retour için zorunlu.', null=True, upload_to='stock_adjustments/', verbose_name='Document justificatif')),
                ('performed_at', models.DateTimeField(verbose_name='Zaman')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment', to='inventory.stockmovement', verbose_name='Stok hareketi')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Yapan')),
            ],
            options={
                'verbose_name': 'Ajustement de stock',
                'verbose_name_plural': 'Ajustements de stock',
                'ordering': ['-performed_at'],
            },
        ),
    ]
