# Generated by Django 5.1.15 on 2026-08-21 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sprint6_stock_adjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='document_source',
            field=models.CharField(blank=True, help_text="Belge kaynağı — Ör. 'Ordre de Production OP-2026-0001', 'Ajustement ADJ-2026-0002'.", max_length=200, verbose_name='Document source'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Hareket anındaki birim fiyat (varsa).', max_digits=12, null=True, verbose_name='Prix unitaire'),
        ),
    ]
