# Generated by Django 5.1.15 on 2026-08-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_sprint7_stockmovement_enrich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstockadjustment',
            name='delta',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tek satırlık ajustement için qty_after − qty_before.', max_digits=12, verbose_name='Delta'),
        ),
        migrations.AlterField(
            model_name='historicalstockadjustment',
            name='lot',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tek satırlık ajustement için. Multi-line ise lines kullan.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.rawmateriallot', verbose_name='Lot (tek satırlık)'),
        ),
        migrations.AlterField(
            model_name='historicalstockadjustment',
            name='qty_after',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qté après'),
        ),
        migrations.AlterField(
            model_name='historicalstockadjustment',
            name='qty_before',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qté avant'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='delta',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Tek satırlık ajustement için qty_after − qty_before.', max_digits=12, verbose_name='Delta'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='Tek satırlık ajustement için. Multi-line ise lines kullan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.rawmateriallot', verbose_name='Lot (tek satırlık)'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='qty_after',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qté après'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='qty_before',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Qté avant'),
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('qty_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté avant')),
                ('qty_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Qté après')),
                ('delta', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Delta')),
                ('line_reason', models.CharField(blank=True, help_text='Ana motif dışı, bu satıra özel not.', max_length=200, verbose_name='Satır motifi')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment', verbose_name='Ajustement')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_lines', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_line', to='inventory.stockmovement', verbose_name='Stok hareketi')),
            ],
            options={
                'verbose_name': 'Ajustement Satırı',
                'verbose_name_plural': 'Ajustement Satırları',
                'ordering': ['adjustment', 'id'],
            },
        ),
    ]
