# Generated by Django 5.1.15 on 2026-08-09 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Birim')),
                ('method', models.CharField(choices=[('EN_934_2', 'EN 934-2 Genel'), ('EN_ISO_758', 'EN ISO 758 (Yoğunluk)'), ('EN_480_1', 'EN 480-1 (Numune hazırlama)'), ('EN_480_8', 'EN 480-8 (Katı madde %)'), ('EN_480_10', 'EN 480-10 (Klorür)'), ('INTERNAL', 'İç metot')], default='EN_934_2', max_length=32, verbose_name='Metot')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'QC Parametresi',
                'verbose_name_plural': 'QC Parametreleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CertificateOfAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('coa_number', models.CharField(max_length=40, unique=True, verbose_name='COA No')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayım zamanı')),
                ('issued_by', models.CharField(blank=True, max_length=120, verbose_name='Yayımlayan')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ISSUED', 'Yayımlandı'), ('REVOKED', 'İptal')], default='DRAFT', max_length=10, verbose_name='Durum')),
                ('summary', models.TextField(blank=True, verbose_name='Özet / Notlar')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coa', to='production.productionbatch', verbose_name='Parti')),
            ],
            options={
                'verbose_name': 'Analiz Sertifikası (COA)',
                'verbose_name_plural': 'Analiz Sertifikaları (COA)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Alt sınır')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Üst sınır')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Hedef')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Zorunlu')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specs', to='quality.qcparameter', verbose_name='Parametre')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_specs', to='masterdata.product', verbose_name='Ürün')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_specs', to='masterdata.rawmaterial', verbose_name='Hammadde')),
            ],
            options={
                'verbose_name': 'QC Spec',
                'verbose_name_plural': "QC Spec'ler",
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('raw_material__isnull', True)), models.Q(('product__isnull', True), ('raw_material__isnull', False)), _connector='OR'), name='qcspec_product_xor_rawmaterial'), models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('parameter', 'product'), name='qcspec_unique_product'), models.UniqueConstraint(condition=models.Q(('raw_material__isnull', False)), fields=('parameter', 'raw_material'), name='qcspec_unique_rawmaterial')],
            },
        ),
        migrations.CreateModel(
            name='QCTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Ölçüm')),
                ('verdict', models.CharField(choices=[('PASS', 'Geçti'), ('FAIL', 'Kaldı'), ('NA', 'Uygulanamaz')], default='NA', max_length=8, verbose_name='Sonuç')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='Test zamanı')),
                ('tester', models.CharField(blank=True, max_length=120, verbose_name='Testi yapan')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_results', to='production.productionbatch', verbose_name='Üretim Partisi')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_results', to='inventory.rawmateriallot', verbose_name='Hammadde Lotu')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='quality.qcparameter', verbose_name='Parametre')),
            ],
            options={
                'verbose_name': 'QC Test Sonucu',
                'verbose_name_plural': 'QC Test Sonuçları',
                'ordering': ['-tested_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', True), ('lot__isnull', False)), models.Q(('batch__isnull', False), ('lot__isnull', True)), _connector='OR'), name='qcresult_lot_xor_batch')],
            },
        ),
    ]
