# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_historicalmaterialconsumption_and_more'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCertificateOfAnalysis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('coa_number', models.CharField(db_index=True, max_length=40, verbose_name='COA No')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Yayım zamanı')),
                ('issued_by', models.CharField(blank=True, max_length=120, verbose_name='Yayımlayan')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ISSUED', 'Yayımlandı'), ('REVOKED', 'İptal')], default='DRAFT', max_length=10, verbose_name='Durum')),
                ('summary', models.TextField(blank=True, verbose_name='Özet / Notlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionbatch', verbose_name='Parti')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Analiz Sertifikası (COA)',
                'verbose_name_plural': 'historical Analiz Sertifikaları (COA)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
