# Generated by Django 5.1.15 on 2026-08-21 07:56

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_companyprofile_customer_address_and_more'),
        ('quality', '0004_certificateofanalysis_controlled_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSamplingPlan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('code', models.CharField(db_index=True, max_length=40, verbose_name='Plan Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('gate', models.CharField(choices=[('A', 'Gate A (Mal kabul / MP)'), ('B', 'Gate B (Üretim ara / IPC)'), ('C', 'Gate C (Bitmiş ürün / PF)')], max_length=1, verbose_name='Gate')),
                ('trigger', models.CharField(choices=[('on_receipt', 'À la réception'), ('per_bl_line', 'Par ligne de BL'), ('after_mix', 'Après mélange'), ('per_batch', 'Par batch de production'), ('on_shipment', "À l'expédition"), ('scheduled', 'Programmé (calendrier)')], max_length=20, verbose_name='Déclencheur')),
                ('frequency_n', models.PositiveIntegerField(default=1, help_text='Örn. 5 → her 5 partide 1 numune.', verbose_name="Sıklık (her N'de bir)")),
                ('sample_size_rule', models.CharField(help_text="Örn. 'sqrt(N)+1', 'MIL-STD-105E S-2', '3 numune sabit'.", max_length=200, verbose_name='Numune sayısı kuralı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('deactivation_reason', models.TextField(blank=True, verbose_name='Deaktifleştirme sebebi (BR-QA-12)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': "historical Plan d'échantillonnage",
                'verbose_name_plural': "historical Plans d'échantillonnage",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SamplingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Plan Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('gate', models.CharField(choices=[('A', 'Gate A (Mal kabul / MP)'), ('B', 'Gate B (Üretim ara / IPC)'), ('C', 'Gate C (Bitmiş ürün / PF)')], max_length=1, verbose_name='Gate')),
                ('trigger', models.CharField(choices=[('on_receipt', 'À la réception'), ('per_bl_line', 'Par ligne de BL'), ('after_mix', 'Après mélange'), ('per_batch', 'Par batch de production'), ('on_shipment', "À l'expédition"), ('scheduled', 'Programmé (calendrier)')], max_length=20, verbose_name='Déclencheur')),
                ('frequency_n', models.PositiveIntegerField(default=1, help_text='Örn. 5 → her 5 partide 1 numune.', verbose_name="Sıklık (her N'de bir)")),
                ('sample_size_rule', models.CharField(help_text="Örn. 'sqrt(N)+1', 'MIL-STD-105E S-2', '3 numune sabit'.", max_length=200, verbose_name='Numune sayısı kuralı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('deactivation_reason', models.TextField(blank=True, verbose_name='Deaktifleştirme sebebi (BR-QA-12)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': "Plan d'échantillonnage",
                'verbose_name_plural': "Plans d'échantillonnage",
                'ordering': ['code'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='qcspec',
            name='qcspec_unique_product',
        ),
        migrations.RemoveConstraint(
            model_name='qcspec',
            name='qcspec_unique_rawmaterial',
        ),
        migrations.AddField(
            model_name='qcparameter',
            name='decimal_precision',
            field=models.PositiveSmallIntegerField(default=2, help_text='Précision décimales — sonuç girişinde kullanılacak ondalık hane sayısı.', verbose_name='Ondalık hane'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_specs_approved', to=settings.AUTH_USER_MODEL, verbose_name='QA Onaylayan'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='check_at_gate_a',
            field=models.BooleanField(default=False, verbose_name="Gate A'da kontrol"),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='check_at_gate_b',
            field=models.BooleanField(default=False, verbose_name="Gate B'de kontrol"),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='check_at_gate_c',
            field=models.BooleanField(default=False, verbose_name="Gate C'de kontrol"),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_specs_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Yürürlük tarihi'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='CRITIQUE — ihlali kritik NCR açar (BR-QA-05).', verbose_name='Kritik (BR-QA-05)'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Tolerans (%)'),
        ),
        migrations.AddField(
            model_name='qcspec',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versiyon'),
        ),
        migrations.AddField(
            model_name='qctestresult',
            name='gate',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='Gate'),
        ),
        migrations.AddField(
            model_name='qctestresult',
            name='spec_locked',
            field=models.ForeignKey(blank=True, help_text='Numune alındığı andaki spec versiyonu — sonradan spec değişse bile evrilmez.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_results', to='quality.qcspec', verbose_name='Kilitli Spec (BR-QA-04)'),
        ),
        migrations.AddConstraint(
            model_name='qcspec',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('parameter', 'product', 'version'), name='qcspec_unique_product_v'),
        ),
        migrations.AddConstraint(
            model_name='qcspec',
            constraint=models.UniqueConstraint(condition=models.Q(('raw_material__isnull', False)), fields=('parameter', 'raw_material', 'version'), name='qcspec_unique_rawmaterial_v'),
        ),
        migrations.AddConstraint(
            model_name='qcspec',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('product__isnull', False)), fields=('parameter', 'product'), name='qcspec_active_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='qcspec',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('raw_material__isnull', False)), fields=('parameter', 'raw_material'), name='qcspec_active_unique_rawmaterial'),
        ),
        migrations.AddField(
            model_name='historicalsamplingplan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsamplingplan',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='historicalsamplingplan',
            name='raw_material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.rawmaterial', verbose_name='Hammadde'),
        ),
        migrations.AddField(
            model_name='samplingplan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_plans', to='masterdata.product', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='samplingplan',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sampling_plans', to='masterdata.rawmaterial', verbose_name='Hammadde'),
        ),
        migrations.AddConstraint(
            model_name='samplingplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', True), ('raw_material__isnull', False)), models.Q(('product__isnull', False), ('raw_material__isnull', True)), _connector='OR'), name='samplingplan_rm_xor_product'),
        ),
    ]
