# Generated by Django 5.1.15 on 2026-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_sprint2_spec_versioning_sampling'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcparameter',
            name='en480_method_ref',
            field=models.CharField(blank=True, help_text="Örn. 'EN 480-8 (Katı madde %)', 'EN 480-10 (Klorür)', 'ISO 758'.", max_length=80, verbose_name='EN 480 metot referansı'),
        ),
    ]
