# Generated by Django 5.1.15 on 2026-08-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_sprint8_expense_invoice'),
        ('production', '0004_historicalproductionbatch_controlled_code_and_more'),
        ('quality', '0006_sprint9_reach_dop_fpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSiteTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('test_number', models.CharField(max_length=40, unique=True, verbose_name='Test No')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='Proje adı')),
                ('site_location', models.CharField(blank=True, max_length=200, verbose_name='Saha konumu')),
                ('test_date', models.DateField(verbose_name='Test tarihi')),
                ('test_type', models.CharField(choices=[('SLUMP', 'Slump testi'), ('CUBE_7', 'Küp mukavemet 7 gün'), ('CUBE_14', 'Küp mukavemet 14 gün'), ('CUBE_28', 'Küp mukavemet 28 gün'), ('TEMP', 'Sıcaklık'), ('AIR', 'Hava içeriği'), ('DUR', 'Dayanıklılık'), ('OTHER', 'Diğer')], max_length=10, verbose_name='Test tipi')),
                ('measured_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ölçülen değer')),
                ('unit', models.CharField(blank=True, help_text='Örn. MPa (mukavemet), mm (slump), °C (sıcaklık)', max_length=20, verbose_name='Birim')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Hedef değer')),
                ('verdict', models.CharField(choices=[('PASS', 'Geçti'), ('FAIL', 'Kaldı'), ('MARGINAL', 'Sınırda'), ('NA', 'Uygulanamaz')], default='NA', max_length=10, verbose_name='Sonuç')),
                ('tested_by', models.CharField(blank=True, max_length=200, verbose_name='Testi yapan (müşteri/lab)')),
                ('lab_report_file', models.FileField(blank=True, null=True, upload_to='site_tests/%Y/', verbose_name='Lab raporu (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_site_tests', to='production.productionbatch', verbose_name='Üretim partisi (mamul)')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_tests', to='accounting.invoiceline', verbose_name='Fatura satırı (satın alınan)')),
            ],
            options={
                'verbose_name': 'Müşteri Saha Testi',
                'verbose_name_plural': 'Müşteri Saha Testleri',
                'ordering': ['-test_date'],
            },
        ),
    ]
