# Generated by Django 5.1.15 on 2026-08-09 19:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('version', models.PositiveIntegerField(verbose_name='Versiyon')),
                ('base_batch_size', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Referans parti')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='masterdata.product', verbose_name='Ürün')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['product', '-version'],
                'unique_together': {('product', 'version')},
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar (base_batch_size başına)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Tolerans (%)')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_lines', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='formulation.recipe', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete Satırı',
                'verbose_name_plural': 'Reçete Satırları',
                'ordering': ['sequence'],
                'unique_together': {('recipe', 'raw_material')},
            },
        ),
    ]
