# Generated by Django 5.1.15 on 2026-08-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessline', '0001_initial'),
        ('formulation', '0002_historicalrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrecipe',
            name='business_line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='businessline.businessline', verbose_name='İş Kolu'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='businessline.businessline', verbose_name='İş Kolu'),
        ),
    ]
