# Generated by Django 5.1.15 on 2026-08-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0003_historicalrecipe_business_line_recipe_business_line'),
        ('masterdata', '0003_companyprofile_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeline',
            name='is_complement',
            field=models.BooleanField(default=False, help_text="COMPLÉMENT: base_batch_size'a otomatik tamamlar (genelde su).", verbose_name='Tamamlayıcı (§22)'),
        ),
        migrations.AddConstraint(
            model_name='recipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_complement', True)), fields=('recipe',), name='one_complement_per_recipe'),
        ),
    ]
