# Generated by Django 5.1.15 on 2026-08-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='İletişim')),
                ('tax_no', models.CharField(blank=True, max_length=30, verbose_name='Vergi No')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='İletişim')),
                ('tax_no', models.CharField(blank=True, max_length=30, verbose_name='Vergi No')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Ölçü Birimi',
                'verbose_name_plural': 'Ölçü Birimleri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('material_type', models.CharField(choices=[('WATER', 'Su'), ('RETARDER', 'Priz geciktirici'), ('SUPERPLASTICIZER', 'Süperplastikleştirici'), ('ADDITIVE', 'Katkı bileşeni'), ('OTHER', 'Diğer')], default='OTHER', max_length=32, verbose_name='Tip')),
                ('density', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Yoğunluk (kg/L)')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Raf ömrü (gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Hammadde',
                'verbose_name_plural': 'Hammaddeler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('container_type', models.CharField(choices=[('TANK', 'Tank'), ('IBC', 'IBC'), ('REACTOR', 'Reaktör')], max_length=16, verbose_name='Tip')),
                ('capacity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Kapasite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Kap',
                'verbose_name_plural': 'Kaplar',
                'ordering': ['code'],
            },
        ),
    ]
