# Generated by Django 5.1.15 on 2026-08-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessline', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_line',
            field=models.ForeignKey(blank=True, help_text='MCOS BusinessLine (MCS/MPT/MFT/MLTS). Geçiş dönemi için null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='businessline.businessline', verbose_name='İş Kolu'),
        ),
    ]
