# Generated by Django 5.1.15 on 2026-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_product_business_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('legal_name', models.CharField(default='SARL MAPA ALGÉRIE', max_length=200, verbose_name='Yasal ünvan')),
                ('short_name', models.CharField(default='MAPA', max_length=60, verbose_name='Kısa ad')),
                ('tagline', models.CharField(blank=True, default='Sıvı Beton Katkısı Fabrikası', max_length=200, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo (PNG/JPG, max 2MB)')),
                ('address', models.TextField(blank=True, default='Zone Industrielle Blida, Algérie', verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('website', models.URLField(blank=True, verbose_name='Web sitesi')),
                ('tax_no', models.CharField(blank=True, help_text="Numéro d'Identification Fiscale", max_length=30, verbose_name='NIF (Vergi kimlik no)')),
                ('tax_activity_no', models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=30, verbose_name='NIS (İstatistik no)')),
                ('trade_register_no', models.CharField(blank=True, help_text='Registre du Commerce', max_length=40, verbose_name='RC (Ticaret sicil no)')),
                ('article_of_import_no', models.CharField(blank=True, max_length=30, verbose_name='Article No')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banka')),
                ('bank_rib', models.CharField(blank=True, help_text="Relevé d'Identité Bancaire", max_length=40, verbose_name='RIB (Cezayir hesap kimlik)')),
                ('bank_iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('invoice_header_note', models.TextField(blank=True, verbose_name='Fatura üst notu')),
                ('invoice_footer_note', models.TextField(blank=True, default='Ödeme vadesi 30 gün. Geç ödemelerde faiz uygulanır.', verbose_name='Fatura alt notu (ödeme koşulları vs.)')),
            ],
            options={
                'verbose_name': 'Şirket Profili',
                'verbose_name_plural': 'Şirket Profili',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='customer',
            name='default_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bu müşteriye faturada otomatik uygulanacak iskonto (0-100).', max_digits=5, verbose_name='Varsayılan iskonto (%)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
    ]
