# Generated by Django 5.1.15 on 2026-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_companyprofile_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bu miktarın altına düşerse sarı alarm (uyarı) verilir.', max_digits=12, verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='rupture_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bu miktarın altına düşerse kırmızı alarm (kritik) verilir.', max_digits=12, verbose_name='Seuil de rupture'),
        ),
    ]
