# Generated by Django 5.1.15 on 2026-08-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_sprint4_stock_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='cas_number',
            field=models.CharField(blank=True, help_text='Chemical Abstracts Service — Ör. 9003-01-4', max_length=20, verbose_name='CAS numarası'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='ec_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='EC numarası'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='reach_registration_no',
            field=models.CharField(blank=True, help_text='01-XXXXXXXXXX-XX-XXXX formatında ECHA registration number.', max_length=40, verbose_name='REACH kayıt no'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='svhc_flag',
            field=models.BooleanField(default=False, help_text='Substance of Very High Concern — REACH downstream notification zorunlu.', verbose_name='REACH SVHC'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='svhc_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='SVHC bileşik oranı — >0.1% ise downstream users bilgilendirilir.', max_digits=6, null=True, verbose_name='SVHC oranı (%)'),
        ),
    ]
