# Generated by Django 5.1.15 on 2026-08-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_sprint9_reach_dop_fpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bitmiş ürün stok uyarı eşiği.', max_digits=12, verbose_name="Seuil d'alerte (mamul)"),
        ),
        migrations.AddField(
            model_name='product',
            name='rupture_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Seuil de rupture (mamul)'),
        ),
    ]
