# Generated by Django 5.1.15 on 2026-08-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulation', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('batch_number', models.CharField(max_length=60, unique=True, verbose_name='Parti No (Mamul Lot)')),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hedef miktar')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Gerçek miktar')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Devam ediyor'), ('COMPLETED', 'Tamamlandı'), ('QC_HOLD', 'Kalite bekletme'), ('RELEASED', 'Serbest bırakıldı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=16, verbose_name='Durum')),
                ('operator', models.CharField(blank=True, max_length=120, verbose_name='Operatör')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('qc_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RELEASED', 'Serbest'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16, verbose_name='Kalite durumu')),
                ('qc_notes', models.TextField(blank=True, verbose_name='Kalite notu')),
                ('reactor', models.ForeignKey(limit_choices_to={'container_type': 'REACTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='masterdata.container', verbose_name='Reaktör')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='formulation.recipe', verbose_name='Reçete (snapshot)')),
            ],
            options={
                'verbose_name': 'Üretim Partisi',
                'verbose_name_plural': 'Üretim Partileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutputContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='Dolum zamanı')),
                ('shipment_reference', models.CharField(blank=True, max_length=120, verbose_name='Sevkiyat referansı')),
                ('container', models.ForeignKey(limit_choices_to={'container_type': 'IBC'}, on_delete=django.db.models.deletion.PROTECT, related_name='output_fillings', to='masterdata.container', verbose_name='Kap (IBC)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='production.productionbatch', verbose_name='Parti')),
            ],
            options={
                'verbose_name': 'Mamul Çıkış Kabı',
                'verbose_name_plural': 'Mamul Çıkış Kapları',
                'ordering': ['-filled_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('target_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hedef ağırlık')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Gerçek ağırlık')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('dosed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dozaj zamanı')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('SCADA', 'SCADA')], default='MANUAL', max_length=10, verbose_name='Kaynak')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='masterdata.rawmaterial', verbose_name='Hammadde')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.productionbatch', verbose_name='Parti')),
            ],
            options={
                'verbose_name': 'Malzeme Tüketimi',
                'verbose_name_plural': 'Malzeme Tüketimleri',
                'ordering': ['batch', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='Emir No')),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hedef miktar')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='Planlanan tarih')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('RELEASED', 'Serbest bırakıldı'), ('IN_PROGRESS', 'Devam ediyor'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masterdata.product', verbose_name='Ürün')),
                ('reactor', models.ForeignKey(limit_choices_to={'container_type': 'REACTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masterdata.container', verbose_name='Reaktör')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='formulation.recipe', verbose_name='Reçete')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Üretim Emri',
                'verbose_name_plural': 'Üretim Emirleri',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='production.productionorder', verbose_name='Üretim emri'),
        ),
    ]
