# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0002_historicalrecipe'),
        ('inventory', '0003_historicalrawmateriallot'),
        ('masterdata', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterialConsumption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('target_weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hedef ağırlık')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Gerçek ağırlık')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='Sıra')),
                ('dosed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dozaj zamanı')),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('SCADA', 'SCADA')], default='MANUAL', max_length=10, verbose_name='Kaynak')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionbatch', verbose_name='Parti')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('raw_material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.rawmaterial', verbose_name='Hammadde')),
            ],
            options={
                'verbose_name': 'historical Malzeme Tüketimi',
                'verbose_name_plural': 'historical Malzeme Tüketimleri',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductionBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('batch_number', models.CharField(db_index=True, max_length=60, verbose_name='Parti No (Mamul Lot)')),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Hedef miktar')),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Gerçek miktar')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('IN_PROGRESS', 'Devam ediyor'), ('COMPLETED', 'Tamamlandı'), ('QC_HOLD', 'Kalite bekletme'), ('RELEASED', 'Serbest bırakıldı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=16, verbose_name='Durum')),
                ('operator', models.CharField(blank=True, max_length=120, verbose_name='Operatör')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlama')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('qc_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('RELEASED', 'Serbest'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16, verbose_name='Kalite durumu')),
                ('qc_notes', models.TextField(blank=True, verbose_name='Kalite notu')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.productionorder', verbose_name='Üretim emri')),
                ('reactor', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'container_type': 'REACTOR'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.container', verbose_name='Reaktör')),
                ('recipe', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formulation.recipe', verbose_name='Reçete (snapshot)')),
            ],
            options={
                'verbose_name': 'historical Üretim Partisi',
                'verbose_name_plural': 'historical Üretim Partileri',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
