# Generated by Django 5.1.15 on 2026-08-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulation', '0004_sprint1_complement_scale'),
        ('masterdata', '0005_sprint9_reach_dop_fpc'),
        ('production', '0004_historicalproductionbatch_controlled_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('campaign_number', models.CharField(max_length=40, unique=True, verbose_name='Campaign No')),
                ('planned_batch_count', models.PositiveIntegerField(help_text='Kampanya boyunca üretilecek toplam parti sayısı.', verbose_name='Planlanan parti sayısı')),
                ('completed_batch_count', models.PositiveIntegerField(default=0, verbose_name='Tamamlanan parti')),
                ('total_target_qty', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Toplam hedef')),
                ('scheduled_start', models.DateField(verbose_name='Başlangıç')),
                ('scheduled_end', models.DateField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('RUNNING', 'Devam ediyor'), ('PAUSED', 'Duraklatıldı'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=12, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='masterdata.product', verbose_name='Ürün')),
                ('reactor', models.ForeignKey(limit_choices_to={'container_type': 'REACTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='masterdata.container', verbose_name='Reaktör')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='formulation.recipe', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Production Campaign',
                'verbose_name_plural': 'Production Campaigns',
                'ordering': ['-scheduled_start'],
            },
        ),
    ]
