# Generated by Django 5.1.15 on 2026-08-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0003_capa_controlled_code_historicalcapa_controlled_code_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capas', to='records.case', verbose_name='MCOS Case'),
        ),
        migrations.AddField(
            model_name='capa',
            name='record_instance',
            field=models.ForeignKey(blank=True, help_text='CAPA form kaydı (örn. MAPA-IMS-FRM-CAPA-001).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='records.recordinstance', verbose_name='MCOS Record Instance'),
        ),
        migrations.AddField(
            model_name='historicalcapa',
            name='case',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.case', verbose_name='MCOS Case'),
        ),
        migrations.AddField(
            model_name='historicalcapa',
            name='record_instance',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='CAPA form kaydı (örn. MAPA-IMS-FRM-CAPA-001).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.recordinstance', verbose_name='MCOS Record Instance'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='case',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="NCR bir MCOS case'e bağlı olabilir (Faz D).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.case', verbose_name='MCOS Case'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='case',
            field=models.ForeignKey(blank=True, help_text="NCR bir MCOS case'e bağlı olabilir (Faz D).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='records.case', verbose_name='MCOS Case'),
        ),
    ]
