# Generated by Django 5.1.15 on 2026-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0004_capa_case_capa_record_instance_historicalcapa_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnonconformance',
            name='gate',
            field=models.CharField(blank=True, choices=[('A', 'Gate A (Mal kabul)'), ('B', 'Gate B (Üretim ara)'), ('C', 'Gate C (Bitmiş ürün)')], max_length=1, verbose_name='Gate'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='proof_document',
            field=models.TextField(blank=True, help_text='Retour fournisseur / Rebut / Dérogation için zorunlu.', max_length=100, null=True, verbose_name='Justificatif (BR-QA-11)'),
        ),
        migrations.AddField(
            model_name='historicalnonconformance',
            name='root_cause_category',
            field=models.CharField(blank=True, choices=[('SUPPLIER_QUALITY', 'Qualité fournisseur'), ('EQUIPMENT', 'Équipement'), ('PROCESS_OPERATOR', 'Process / Opérateur'), ('FORMULA_DESIGN', 'Conception formule'), ('MEASUREMENT_ERROR', 'Erreur de mesure / échantillonnage'), ('ENVIRONMENTAL', 'Environnemental'), ('OTHER', 'Autre')], max_length=24, verbose_name='Root cause category'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='gate',
            field=models.CharField(blank=True, choices=[('A', 'Gate A (Mal kabul)'), ('B', 'Gate B (Üretim ara)'), ('C', 'Gate C (Bitmiş ürün)')], max_length=1, verbose_name='Gate'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Retour fournisseur / Rebut / Dérogation için zorunlu.', null=True, upload_to='ncr_proofs/', verbose_name='Justificatif (BR-QA-11)'),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='root_cause_category',
            field=models.CharField(blank=True, choices=[('SUPPLIER_QUALITY', 'Qualité fournisseur'), ('EQUIPMENT', 'Équipement'), ('PROCESS_OPERATOR', 'Process / Opérateur'), ('FORMULA_DESIGN', 'Conception formule'), ('MEASUREMENT_ERROR', 'Erreur de mesure / échantillonnage'), ('ENVIRONMENTAL', 'Environnemental'), ('OTHER', 'Autre')], max_length=24, verbose_name='Root cause category'),
        ),
        migrations.AlterField(
            model_name='historicalnonconformance',
            name='disposition',
            field=models.CharField(choices=[('PENDING', 'Karar bekliyor'), ('USE_AS_IS', 'Olduğu gibi kullan (concession)'), ('REWORK', 'Yeniden işle'), ('REJECT', 'Reddet / imha (Rebut)'), ('RETURN_TO_SUPPLIER', 'Tedarikçiye iade'), ('DOWNGRADE', 'Sınıf düşür'), ('WAIVER', 'Dérogation (waiver)')], default='PENDING', max_length=20, verbose_name='Karar (disposition)'),
        ),
        migrations.AlterField(
            model_name='nonconformance',
            name='disposition',
            field=models.CharField(choices=[('PENDING', 'Karar bekliyor'), ('USE_AS_IS', 'Olduğu gibi kullan (concession)'), ('REWORK', 'Yeniden işle'), ('REJECT', 'Reddet / imha (Rebut)'), ('RETURN_TO_SUPPLIER', 'Tedarikçiye iade'), ('DOWNGRADE', 'Sınıf düşür'), ('WAIVER', 'Dérogation (waiver)')], default='PENDING', max_length=20, verbose_name='Karar (disposition)'),
        ),
    ]
