# Generated by Django 5.1.15 on 2026-08-09 19:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('order_number', models.CharField(max_length=40, unique=True, verbose_name='Sipariş No')),
                ('order_date', models.DateField(verbose_name='Sipariş tarihi')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Sevk tarihi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('CONFIRMED', 'Onaylandı'), ('PARTIAL', 'Kısmi sevk'), ('SHIPPED', 'Sevk edildi'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='masterdata.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Siparişi',
                'verbose_name_plural': 'Müşteri Siparişleri',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar')),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Birim fiyat')),
                ('shipped_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='Sevk edilen miktar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_lines', to='masterdata.product', verbose_name='Ürün')),
                ('so', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='Sipariş')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_lines', to='masterdata.unitofmeasure', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'SO Satırı',
                'verbose_name_plural': 'SO Satırları',
                'unique_together': {('so', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('shipment_number', models.CharField(max_length=40, unique=True, verbose_name='Sevk No / İrsaliye')),
                ('shipped_date', models.DateField(verbose_name='Sevk tarihi')),
                ('carrier', models.CharField(blank=True, max_length=120, verbose_name='Taşıyıcı')),
                ('vehicle_plate', models.CharField(blank=True, max_length=30, verbose_name='Araç plaka')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='masterdata.customer', verbose_name='Müşteri')),
                ('so', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='sales.salesorder', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Sevkiyat',
                'verbose_name_plural': 'Sevkiyatlar',
                'ordering': ['-shipped_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Miktar')),
                ('output_container', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_line', to='production.outputcontainer', verbose_name='Mamul IBC')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.shipment', verbose_name='Sevkiyat')),
                ('so_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_lines', to='sales.salesorderline', verbose_name='SO Satırı')),
            ],
            options={
                'verbose_name': 'Sevkiyat Satırı',
                'verbose_name_plural': 'Sevkiyat Satırları',
            },
        ),
    ]
