# Generated by Django 5.1.15 on 2026-08-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_historicalinvoice_discount_amount_and_more'),
        ('sales', '0002_salesorder_business_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-shipped_date', '-created_at'], 'verbose_name': 'BL Client (İrsaliye)', 'verbose_name_plural': 'BL Clients (İrsaliyeler)'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Teslim adresi'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Şoför'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='accounting.invoice', verbose_name='Bağlı Fatura'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Taslak'), ('DELIVERED', 'Teslim edildi'), ('INVOICED', 'Faturalandı'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(max_length=40, unique=True, verbose_name='BL / Sevk No'),
        ),
    ]
