# Generated by Django 5.1.15 on 2026-08-21 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_sprint9_reach_dop_fpc'),
        ('sales', '0003_sprint3_bl_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicatorTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('training_number', models.CharField(max_length=40, unique=True, verbose_name='Training No')),
                ('training_date', models.DateField(verbose_name='Eğitim tarihi')),
                ('location', models.CharField(max_length=200, verbose_name='Yer')),
                ('topics', models.TextField(help_text='Örn. dozaj kalibrasyonu, slump yönetimi, güvenlik prosedürleri.', verbose_name='Konu başlıkları')),
                ('products_covered', models.CharField(blank=True, max_length=300, verbose_name='İşlenen ürünler')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='Katılımcı sayısı')),
                ('participant_list', models.TextField(blank=True, help_text='Her satır bir kişi (ad soyad · görev)', verbose_name='Katılımcı listesi')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Süre (saat)')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Katılım belgesi verildi')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='trainings/%Y/', verbose_name='Toplu katılım belgesi (PDF)')),
                ('feedback_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Geri bildirim puanı (1-5)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicator_trainings', to='masterdata.customer')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings_delivered', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen')),
            ],
            options={
                'verbose_name': 'Applicator Training',
                'verbose_name_plural': 'Applicator Trainings',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='MixDesignConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('consultation_number', models.CharField(max_length=40, unique=True, verbose_name='Consultation No')),
                ('request_date', models.DateField(verbose_name='Talep tarihi')),
                ('project_name', models.CharField(help_text='Ör. Otoyol köprüsü Sétif, Baraj enjeksiyonu Béjaïa', max_length=200, verbose_name='Proje adı')),
                ('concrete_class_target', models.CharField(help_text='Ör. C30/37, C40/50, C50/60', max_length=40, verbose_name='Beton sınıfı hedefi')),
                ('special_requirements', models.TextField(help_text='Sıcak iklim, deniz suyu maruziyeti, erken dayanım, vs.', verbose_name='Özel gereksinimler')),
                ('proposed_products', models.CharField(blank=True, max_length=300, verbose_name='Önerilen ürün(ler)')),
                ('proposed_dosage', models.CharField(blank=True, max_length=200, verbose_name='Önerilen doz')),
                ('report', models.FileField(blank=True, null=True, upload_to='mix_designs/%Y/', verbose_name='Öneri raporu (PDF)')),
                ('status', models.CharField(choices=[('REQUESTED', 'Talep alındı'), ('IN_STUDY', 'Çalışılıyor'), ('DELIVERED', 'Rapor teslim edildi'), ('IMPLEMENTED', 'Sahada uygulandı')], default='REQUESTED', max_length=12, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_design_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Teknik danışman')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_design_consultations', to='masterdata.customer')),
            ],
            options={
                'verbose_name': 'Mix Design Consultation',
                'verbose_name_plural': 'Mix Design Consultations',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('warranty_number', models.CharField(max_length=40, unique=True, verbose_name='Warranty No')),
                ('project_name', models.CharField(max_length=200, verbose_name='Proje adı')),
                ('project_location', models.CharField(blank=True, max_length=200, verbose_name='Proje konumu')),
                ('quantity_supplied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Teslim edilen miktar')),
                ('warranty_start', models.DateField(verbose_name='Garanti başlangıcı')),
                ('warranty_end', models.DateField(verbose_name='Garanti sonu')),
                ('coverage_summary', models.TextField(help_text='Örn. 25 yıl dayanıklılık, dosaj koşulları, güvenlik sınırları.', verbose_name='Kapsam özeti')),
                ('exclusions', models.TextField(blank=True, help_text='Yanlış uygulama, uygun olmayan koşullar vb.', verbose_name='Hariç durumlar')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='İmza zamanı')),
                ('document', models.FileField(blank=True, null=True, upload_to='warranties/%Y/', verbose_name='Garanti belgesi (PDF)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('EXPIRED', 'Süresi doldu'), ('CLAIMED', 'Talep açıldı'), ('VOIDED', 'Geçersiz kılındı')], default='ACTIVE', max_length=10, verbose_name='Durum')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='masterdata.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='masterdata.product')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties_signed', to=settings.AUTH_USER_MODEL, verbose_name='İmza sahibi')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_units', to='masterdata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Performance Warranty',
                'verbose_name_plural': 'Performance Warranties',
                'ordering': ['-warranty_start'],
            },
        ),
        migrations.CreateModel(
            name='TrialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('trial_number', models.CharField(max_length=40, unique=True, verbose_name='Trial No')),
                ('trial_date', models.DateField(verbose_name='Deneme tarihi')),
                ('sample_quantity', models.DecimalField(decimal_places=2, help_text='Ör. 25 kg — küçük deneme paketi.', max_digits=10, verbose_name='Numune miktarı')),
                ('site_address', models.CharField(blank=True, help_text='Deneme yapılacak inşaat/santral konumu.', max_length=300, verbose_name='Saha adresi')),
                ('customer_cement_brand', models.CharField(blank=True, max_length=120, verbose_name='Müşteri çimento markası')),
                ('customer_cement_class', models.CharField(blank=True, help_text='Ör. CEM I 42.5 R, CEM II B-M 32.5 N', max_length=40, verbose_name='Çimento sınıfı')),
                ('aggregate_max_size', models.CharField(blank=True, max_length=20, verbose_name='Agrega max boyutu')),
                ('target_slump', models.CharField(blank=True, help_text='Ör. S3 (100-150 mm), S4 (160-210 mm)', max_length=40, verbose_name='Hedef slump')),
                ('target_wc_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Hedef w/c oranı')),
                ('dosage_pct', models.DecimalField(blank=True, decimal_places=3, help_text='Çimento ağırlığına göre önerilen doz.', max_digits=5, null=True, verbose_name='Doz (%)')),
                ('initial_slump', models.CharField(blank=True, max_length=20, verbose_name='İlk slump (mm)')),
                ('slump_30min', models.CharField(blank=True, max_length=20, verbose_name='30 dk slump (mm)')),
                ('slump_60min', models.CharField(blank=True, max_length=20, verbose_name='60 dk slump (mm)')),
                ('slump_90min', models.CharField(blank=True, max_length=20, verbose_name='90 dk slump (mm)')),
                ('site_temperature', models.CharField(blank=True, max_length=20, verbose_name='Saha sıcaklığı (°C)')),
                ('trial_notes', models.TextField(blank=True, help_text='Müşteri geri bildirimi + saha ekibi gözlemleri.', verbose_name='Saha ekibi notları')),
                ('status', models.CharField(choices=[('PLANNED', 'Planlandı'), ('SHIPPED', 'Numune gönderildi'), ('IN_TRIAL', 'Saha testinde'), ('SUCCESS', 'Başarılı (sipariş uygun)'), ('FAILED', 'Başarısız'), ('CANCELLED', 'İptal')], default='PLANNED', max_length=12, verbose_name='Durum')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_batches', to='masterdata.customer', verbose_name='Müşteri')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials_performed', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_batches', to='masterdata.product', verbose_name='Ürün adayı')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_units', to='masterdata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Trial Batch',
                'verbose_name_plural': 'Trial Batches',
                'ordering': ['-trial_date'],
            },
        ),
    ]
