# Generated by Django 5.1.15 on 2026-08-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sprint10_customer_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('plate_number', models.CharField(max_length=30, unique=True, verbose_name='Plaka')),
                ('truck_type', models.CharField(choices=[('TANKER', 'Tanker (dökme sıvı)'), ('FLATBED', 'Platform (IBC)'), ('VAN', 'Kamyonet (paket)'), ('REEFER', 'Soğutmalı')], max_length=10, verbose_name='Tip')),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kapasite (kg)')),
                ('make_model', models.CharField(blank=True, max_length=120, verbose_name='Marka/model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yıl')),
                ('driver_default', models.CharField(blank=True, max_length=200, verbose_name='Varsayılan şoför')),
                ('driver_phone', models.CharField(blank=True, max_length=30, verbose_name='Şoför telefonu')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Müsait'), ('LOADING', 'Yükleniyor'), ('EN_ROUTE', 'Yolda'), ('UNLOADING', 'Boşaltılıyor'), ('MAINTENANCE', 'Bakımda'), ('OUT', 'Servis dışı')], default='AVAILABLE', max_length=12, verbose_name='Durum')),
                ('gps_device_id', models.CharField(blank=True, help_text='Filo takip cihazı ID — API sorgu anahtarı.', max_length=80, verbose_name='GPS cihaz ID')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Son bakım')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Sonraki bakım')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Truck (Camion)',
                'verbose_name_plural': 'Trucks (Camions)',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('trip_number', models.CharField(max_length=40, unique=True, verbose_name='Trip No')),
                ('driver_name', models.CharField(blank=True, max_length=200, verbose_name='Şoför')),
                ('driver_phone', models.CharField(blank=True, max_length=30, verbose_name='Şoför telefonu')),
                ('scheduled_departure', models.DateTimeField(verbose_name='Planlanan çıkış')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek çıkış')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='Planlanan varış')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek varış')),
                ('delivery_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim tamamlandı')),
                ('origin_address', models.CharField(default='Fabrika — Zone industrielle Rouiba, Alger', max_length=300, verbose_name='Yükleme yeri')),
                ('destination_address', models.CharField(max_length=300, verbose_name='Teslim yeri')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Mesafe (km)')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yakıt gideri (DZD)')),
                ('last_gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Son GPS enlem')),
                ('last_gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Son GPS boylam')),
                ('last_gps_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Son GPS zamanı')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planlandı'), ('LOADED', 'Yüklendi'), ('DEPARTED', 'Yola çıktı'), ('ARRIVED', 'Teslim yerine ulaştı'), ('DELIVERED', 'Teslim edildi'), ('RETURNED', 'Geri döndü'), ('CANCELLED', 'İptal')], default='SCHEDULED', max_length=12, verbose_name='Durum')),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='pods/%Y/%m/', verbose_name='POD (imzalı belge)')),
                ('signature_name', models.CharField(blank=True, max_length=200, verbose_name='Teslim alan (ad soyad)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_trip', to='sales.shipment', verbose_name='BL Client')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='sales.truck', verbose_name='Kamyon')),
            ],
            options={
                'verbose_name': 'Delivery Trip',
                'verbose_name_plural': 'Delivery Trips',
                'ordering': ['-scheduled_departure'],
            },
        ),
    ]
