# Generated by Django 5.1.15 on 2026-08-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('protocol', models.CharField(choices=[('MOCK', 'Mock (test)'), ('OPC_UA', 'OPC UA'), ('MODBUS_TCP', 'Modbus TCP'), ('MQTT', 'MQTT')], default='MOCK', max_length=12, verbose_name='Protokol')),
                ('host', models.CharField(blank=True, max_length=120, verbose_name='Host / IP')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Port')),
                ('endpoint_url', models.CharField(blank=True, help_text='opc.tcp://... veya mqtt://... veya modbus.tcp://host:port/unit', max_length=255, verbose_name='Endpoint URL')),
                ('credentials_env', models.CharField(blank=True, help_text='Kullanıcı/şifre bu env değişkeninden okunur.', max_length=80, verbose_name='Kimlik env anahtarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'PLC Endpoint',
                'verbose_name_plural': "PLC Endpoint'ler",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RecipeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('SENT', 'Gönderildi'), ('FAILED', 'Başarısız'), ('SIMULATED', 'Simüle edildi')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim zamanı')),
                ('response', models.TextField(blank=True, verbose_name='PLC yanıtı')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_downloads', to='production.productionbatch', verbose_name='Parti')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_downloads', to='scada.plcendpoint', verbose_name='Endpoint')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_downloads', to='production.productionorder', verbose_name='Üretim Emri')),
            ],
            options={
                'verbose_name': 'Reçete İndirme',
                'verbose_name_plural': 'Reçete İndirmeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeighmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('tag', models.CharField(help_text='Format: <batch_number>.<material_code> (örn. BATCH-005.SP)', max_length=120, verbose_name='Tag / adres')),
                ('weight', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Ağırlık')),
                ('plc_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='PLC zaman damgası')),
                ('status', models.CharField(choices=[('RECEIVED', 'Alındı'), ('MATCHED', 'Eşleşti'), ('UNMATCHED', 'Eşleşmedi'), ('FAILED', 'Hata')], default='RECEIVED', max_length=12, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata mesajı')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Ham veri')),
                ('consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighment_events', to='production.materialconsumption', verbose_name='Eşlenen tüketim')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weighments', to='scada.plcendpoint', verbose_name='Endpoint')),
            ],
            options={
                'verbose_name': 'Tartım Eventi',
                'verbose_name_plural': "Tartım Event'leri",
                'ordering': ['-created_at'],
            },
        ),
    ]
