# Generated by Django 5.1.15 on 2026-08-09 19:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('prefix', models.CharField(help_text='Doküman numarasında kullanılır (örn. SOP, WI, F, POL).', max_length=10, verbose_name='Numara ön eki')),
            ],
            options={
                'verbose_name': 'Doküman Kategorisi',
                'verbose_name_plural': 'Doküman Kategorileri',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ControlledDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('document_number', models.CharField(max_length=40, unique=True, verbose_name='Doküman No')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('RETIRED', 'Geri çekildi')], default='ACTIVE', max_length=8, verbose_name='Durum')),
                ('retention_years', models.PositiveIntegerField(default=10, help_text='ISO 9001 §7.5 gereği saklama süresi.', verbose_name='Saklama süresi (yıl)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('process_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL, verbose_name='Süreç sahibi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='docs.documentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kontrollü Doküman',
                'verbose_name_plural': 'Kontrollü Dokümanlar',
                'ordering': ['document_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('revision', models.CharField(help_text='Örn. 01, 02, A, B', max_length=10, verbose_name='Revizyon')),
                ('file', models.FileField(blank=True, help_text='PDF veya diğer dosya. Sistemin ağ paylaşımından da referanslanabilir.', null=True, upload_to='docs/%Y/%m/', verbose_name='Dosya')),
                ('external_url', models.URLField(blank=True, help_text='Dosya yerine harici link (opsiyonel).', verbose_name='Harici URL')),
                ('change_summary', models.TextField(verbose_name='Değişiklik özeti')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REVIEW', 'İnceleme'), ('APPROVED', 'Onaylandı'), ('EFFECTIVE', 'Yürürlükte'), ('SUPERSEDED', 'Yerine yenisi geldi'), ('WITHDRAWN', 'Geri çekildi')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme zamanı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük tarihi')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Sonraki gözden geçirme')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='docs.controlleddocument', verbose_name='Doküman')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Hazırlayan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_revisions', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'Doküman Revizyonu',
                'verbose_name_plural': 'Doküman Revizyonları',
                'ordering': ['document', '-effective_date'],
                'unique_together': {('document', 'revision')},
            },
        ),
        migrations.CreateModel(
            name='DocumentDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('department_code', models.CharField(blank=True, max_length=20, verbose_name='Departman kodu')),
                ('copy_number', models.CharField(blank=True, help_text='Kontrollü basılı kopya için sıra numarası.', max_length=20, verbose_name='Kopya no')),
                ('distributed_at', models.DateTimeField(auto_now_add=True, verbose_name='Dağıtım zamanı')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='Geri çekme zamanı')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='docs.documentrevision', verbose_name='Revizyon')),
            ],
            options={
                'verbose_name': 'Doküman Dağıtımı',
                'verbose_name_plural': 'Doküman Dağıtımları',
            },
        ),
        migrations.CreateModel(
            name='HistoricalControlledDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('document_number', models.CharField(db_index=True, max_length=40, verbose_name='Doküman No')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('RETIRED', 'Geri çekildi')], default='ACTIVE', max_length=8, verbose_name='Durum')),
                ('retention_years', models.PositiveIntegerField(default=10, help_text='ISO 9001 §7.5 gereği saklama süresi.', verbose_name='Saklama süresi (yıl)')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docs.documentcategory', verbose_name='Kategori')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process_owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Süreç sahibi')),
            ],
            options={
                'verbose_name': 'historical Kontrollü Doküman',
                'verbose_name_plural': 'historical Kontrollü Dokümanlar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentRevision',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('revision', models.CharField(help_text='Örn. 01, 02, A, B', max_length=10, verbose_name='Revizyon')),
                ('file', models.TextField(blank=True, help_text='PDF veya diğer dosya. Sistemin ağ paylaşımından da referanslanabilir.', max_length=100, null=True, verbose_name='Dosya')),
                ('external_url', models.URLField(blank=True, help_text='Dosya yerine harici link (opsiyonel).', verbose_name='Harici URL')),
                ('change_summary', models.TextField(verbose_name='Değişiklik özeti')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('REVIEW', 'İnceleme'), ('APPROVED', 'Onaylandı'), ('EFFECTIVE', 'Yürürlükte'), ('SUPERSEDED', 'Yerine yenisi geldi'), ('WITHDRAWN', 'Geri çekildi')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme zamanı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='Yürürlük tarihi')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Sonraki gözden geçirme')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docs.controlleddocument', verbose_name='Doküman')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Hazırlayan')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'historical Doküman Revizyonu',
                'verbose_name_plural': 'historical Doküman Revizyonları',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Onay zamanı')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='docs.documentrevision', verbose_name='Revizyon')),
            ],
            options={
                'verbose_name': 'Doküman Okundu Onayı',
                'verbose_name_plural': 'Doküman Okundu Onayları',
                'unique_together': {('revision', 'user')},
            },
        ),
    ]
