# Generated by Django 5.1.15 on 2026-08-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_controlleddocument_business_line_and_more'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlleddocument',
            name='controlled_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='registry.controlledcode', verbose_name='MCOS Kontrollü Kod'),
        ),
        migrations.AddField(
            model_name='historicalcontrolleddocument',
            name='controlled_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.controlledcode', verbose_name='MCOS Kontrollü Kod'),
        ),
    ]
