# Generated by Django 5.1.15 on 2026-08-15 18:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessline', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('gate_id', models.CharField(help_text='Örn. "GATE-001", "GATE-BATCH-2026-0001"', max_length=40, unique=True, verbose_name='Gate ID')),
                ('scope', models.TextField(help_text='Bu kapının kapsadığı olay/karar/geçişin özeti.', verbose_name='Kapsam')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('HOLD', 'HOLD'), ('CONDITIONAL', 'Conditional PASS'), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REOPENED', 'Reopened')], default='OPEN', max_length=12, verbose_name='Durum')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanma')),
                ('reopen_history', models.JSONField(blank=True, default=list, help_text='[{trigger, by_user, at, note}, ...]', verbose_name='Yeniden açma geçmişi')),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gates', to='businessline.businessline')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gates', to='records.case')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_gates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_gates', to=settings.AUTH_USER_MODEL, verbose_name='Kapı sahibi')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': "Gate'ler (8-Part)",
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='GateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('section', models.CharField(choices=[('OPERATION', '1. Operation'), ('IMS_ENGINE', '2. IMS Engine'), ('DECISION_ARCH', '3. Decision Architecture'), ('OBJECTIVE_EVIDENCE', '4. Objective Evidence'), ('MANAGEMENT_REVIEW', '5. Management Review'), ('LESSONS_LEARNED', '6. Lessons Learned'), ('IMS_IMPROVEMENT', '7. IMS Improvement'), ('GATE_STATUS', '8. Gate Status')], max_length=20, verbose_name='Bölüm')),
                ('completion_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('HOLD', 'HOLD'), ('CONDITIONAL', 'Conditional PASS'), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REOPENED', 'Reopened')], default='OPEN', max_length=14, verbose_name='Tamamlanma durumu')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('evidence', models.ManyToManyField(blank=True, related_name='gate_sections', to='records.evidence', verbose_name='Kanıtlar')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='gates.gate')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gate_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gate Section',
                'verbose_name_plural': 'Gate Sections',
                'ordering': ['gate', 'section'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('gate_id', models.CharField(db_index=True, help_text='Örn. "GATE-001", "GATE-BATCH-2026-0001"', max_length=40, verbose_name='Gate ID')),
                ('scope', models.TextField(help_text='Bu kapının kapsadığı olay/karar/geçişin özeti.', verbose_name='Kapsam')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('HOLD', 'HOLD'), ('CONDITIONAL', 'Conditional PASS'), ('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REOPENED', 'Reopened')], default='OPEN', max_length=12, verbose_name='Durum')),
                ('opened_at', models.DateTimeField(blank=True, editable=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanma')),
                ('reopen_history', models.JSONField(blank=True, default=list, help_text='[{trigger, by_user, at, note}, ...]', verbose_name='Yeniden açma geçmişi')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('business_line', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='businessline.businessline')),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='records.case')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kapı sahibi')),
            ],
            options={
                'verbose_name': 'historical Gate',
                'verbose_name_plural': "historical Gate'ler (8-Part)",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='gate',
            index=models.Index(fields=['status'], name='gates_gate_status_c43818_idx'),
        ),
        migrations.AddIndex(
            model_name='gate',
            index=models.Index(fields=['case', 'status'], name='gates_gate_case_id_f435a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gatesection',
            unique_together={('gate', 'section')},
        ),
    ]
