# Generated by Django 5.1.15 on 2026-08-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmms', '0002_equipment_business_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('alert_number', models.CharField(max_length=40, unique=True, verbose_name='Alert No')),
                ('sensor_tag', models.CharField(help_text='SCADA sensör etiketi (Ör. R101.TEMP.OUT).', max_length=80, verbose_name='Sensor tag')),
                ('parameter', models.CharField(help_text='Ör. Temperature, Pressure, RPM, Flow rate.', max_length=60, verbose_name='Ölçüm parametresi')),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Ölçüm değeri')),
                ('threshold_low', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Alt eşik')),
                ('threshold_high', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Üst eşik')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Birim')),
                ('detected_at', models.DateTimeField(verbose_name='Tespit zamanı')),
                ('severity', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('CRITICAL', 'Kritik')], default='WARNING', max_length=8, verbose_name='Şiddet')),
                ('status', models.CharField(choices=[('NEW', 'Yeni'), ('ACK', 'Onaylandı (kabul)'), ('WO_CREATED', 'İş emri açıldı'), ('RESOLVED', 'Çözüldü'), ('IGNORED', 'Görmezden gelindi')], default='NEW', max_length=12, verbose_name='Durum')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm zamanı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('auto_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_alert', to='cmms.workorder', verbose_name='Otomatik açılan iş emri')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensor_alerts', to='cmms.equipment', verbose_name='Ekipman')),
            ],
            options={
                'verbose_name': 'Sensor Alert',
                'verbose_name_plural': 'Sensor Alerts',
                'ordering': ['-detected_at'],
            },
        ),
    ]
