# Generated by Django 5.1.15 on 2026-08-10 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('kind', models.CharField(choices=[('INVOICE_POST', 'Fatura Muhasebeleştirme'), ('BATCH_RELEASE', 'Parti Serbest Bırakma'), ('CAPA_CLOSE', 'CAPA Kapatma'), ('PO_HIGH_AMOUNT', 'Yüksek Tutarlı PO'), ('DOC_APPROVE', 'Doküman Onayı'), ('NCR_DISPOSITION', 'NCR Karar (Disposition)'), ('OTHER', 'Diğer')], max_length=20, verbose_name='Tür')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('object_id', models.PositiveBigIntegerField()),
                ('required_role', models.CharField(help_text='Grup adı — bu roldeki herhangi bir aktif kullanıcı onaylayabilir.', max_length=40, verbose_name='Onaylayacak rol')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Karar zamanı')),
                ('decision_reason', models.CharField(blank=True, max_length=500, verbose_name='Karar gerekçesi')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden')),
            ],
            options={
                'verbose_name': 'Onay Talebi',
                'verbose_name_plural': 'Onay Talepleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'required_role'], name='portal_appr_status_a5ad9d_idx'), models.Index(fields=['content_type', 'object_id'], name='portal_appr_content_949284_idx')],
            },
        ),
    ]
