# Generated by Django 5.1.15 on 2026-08-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='decision_level',
            field=models.CharField(choices=[('D1', 'D1 Routine execution'), ('D2', 'D2 Functional decision'), ('D3', 'D3 Major decision'), ('D4', 'D4 Strategic / crisis')], default='D2', help_text='NAV-002 §3 — talep bu seviyede karar bekliyor.', max_length=2, verbose_name='MCOS karar seviyesi'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='veto_holder_role',
            field=models.CharField(blank=True, help_text='Bu talebe veto edebilecek rol (örn. IMS_QA_MANAGER, HSE_OFFICER). Boşsa veto uygulanmaz.', max_length=60, verbose_name='Veto sahibi rol'),
        ),
    ]
