# Generated by Django 5.1.15 on 2026-08-21 13:23

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_historicalsafetydatasheet_business_line_and_more'),
        ('masterdata', '0005_sprint9_reach_dop_fpc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationOfPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('dop_number', models.CharField(max_length=40, unique=True, verbose_name='DoP No')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versiyon')),
                ('issue_date', models.DateField(verbose_name='Yayım tarihi')),
                ('intended_use', models.CharField(help_text='Örn. Superplasticizer / High Range Water Reducer.', max_length=200, verbose_name='Kullanım amacı')),
                ('performance_data', models.JSONField(default=dict, help_text="EN 934-2 tablo değerleri. Örn.: {'chloride_ion_content': '<=0.1%', 'alkali_content': '<=1.5%', 'water_reduction': '>=12%', 'compressive_strength_ratio_7d': '>=125%'}", verbose_name='Performans karakteristikleri')),
                ('manufacturer_signatory', models.CharField(help_text="Örn. 'A. Bouzidi, Directeur Général'", max_length=200, verbose_name='İmza sahibi (temsilci)')),
                ('file', models.FileField(blank=True, null=True, upload_to='dop/%Y/', verbose_name='DoP PDF')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ISSUED', 'Yayımlandı'), ('SUPERSEDED', 'Yerine yenisi geldi'), ('WITHDRAWN', 'Geri çekildi')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('coc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dops', to='chemicals.certificateofconformity', verbose_name='Bağlı CoC (NB certificate)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dops', to='masterdata.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Declaration of Performance',
                'verbose_name_plural': 'Declarations of Performance',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='FPCAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('audit_number', models.CharField(max_length=40, unique=True, verbose_name='Audit No')),
                ('audit_type', models.CharField(choices=[('INITIAL', 'İlk denetim (initial)'), ('SURVEILLANCE', 'Sürveyans (periyodik)'), ('SPECIAL', 'Özel (şikayet/uyarı sonrası)'), ('RENEWAL', 'Yenileme')], default='SURVEILLANCE', max_length=16, verbose_name='Denetim tipi')),
                ('audit_date', models.DateField(verbose_name='Denetim tarihi')),
                ('auditor_name', models.CharField(max_length=200, verbose_name='Denetçi')),
                ('scope', models.TextField(help_text='Denetlenen ürünler, hatlar, prosesler.', verbose_name='Kapsam')),
                ('findings', models.TextField(blank=True, help_text="Major/minor NC + observation'lar.", verbose_name='Bulgular')),
                ('major_nc_count', models.PositiveIntegerField(default=0, verbose_name='Major NC')),
                ('minor_nc_count', models.PositiveIntegerField(default=0, verbose_name='Minor NC')),
                ('observations_count', models.PositiveIntegerField(default=0, verbose_name='Observation')),
                ('outcome', models.CharField(choices=[('PENDING', 'Beklemede'), ('PASSED', 'Uygun'), ('PASSED_FINDINGS', 'Uygun (bulgu ile)'), ('CONDITIONAL', 'Şartlı'), ('FAILED', 'Uygun değil')], default='PENDING', max_length=20, verbose_name='Sonuç')),
                ('corrective_action_deadline', models.DateField(blank=True, null=True, verbose_name='Düzeltici aksiyon son tarihi')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Düzeltici aksiyon planı')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='fpc_audits/%Y/', verbose_name='Denetim raporu (PDF)')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Sertifika düzenlendi')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='Sonraki denetim')),
                ('notified_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='chemicals.notifiedbody', verbose_name='Onaylanmış Kuruluş')),
            ],
            options={
                'verbose_name': 'FPC Audit',
                'verbose_name_plural': 'FPC Audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeclarationOfPerformance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('dop_number', models.CharField(db_index=True, max_length=40, verbose_name='DoP No')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versiyon')),
                ('issue_date', models.DateField(verbose_name='Yayım tarihi')),
                ('intended_use', models.CharField(help_text='Örn. Superplasticizer / High Range Water Reducer.', max_length=200, verbose_name='Kullanım amacı')),
                ('performance_data', models.JSONField(default=dict, help_text="EN 934-2 tablo değerleri. Örn.: {'chloride_ion_content': '<=0.1%', 'alkali_content': '<=1.5%', 'water_reduction': '>=12%', 'compressive_strength_ratio_7d': '>=125%'}", verbose_name='Performans karakteristikleri')),
                ('manufacturer_signatory', models.CharField(help_text="Örn. 'A. Bouzidi, Directeur Général'", max_length=200, verbose_name='İmza sahibi (temsilci)')),
                ('file', models.TextField(blank=True, max_length=100, null=True, verbose_name='DoP PDF')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('ISSUED', 'Yayımlandı'), ('SUPERSEDED', 'Yerine yenisi geldi'), ('WITHDRAWN', 'Geri çekildi')], default='DRAFT', max_length=12, verbose_name='Durum')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('coc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chemicals.certificateofconformity', verbose_name='Bağlı CoC (NB certificate)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'historical Declaration of Performance',
                'verbose_name_plural': 'historical Declarations of Performance',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFPCAudit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('audit_number', models.CharField(db_index=True, max_length=40, verbose_name='Audit No')),
                ('audit_type', models.CharField(choices=[('INITIAL', 'İlk denetim (initial)'), ('SURVEILLANCE', 'Sürveyans (periyodik)'), ('SPECIAL', 'Özel (şikayet/uyarı sonrası)'), ('RENEWAL', 'Yenileme')], default='SURVEILLANCE', max_length=16, verbose_name='Denetim tipi')),
                ('audit_date', models.DateField(verbose_name='Denetim tarihi')),
                ('auditor_name', models.CharField(max_length=200, verbose_name='Denetçi')),
                ('scope', models.TextField(help_text='Denetlenen ürünler, hatlar, prosesler.', verbose_name='Kapsam')),
                ('findings', models.TextField(blank=True, help_text="Major/minor NC + observation'lar.", verbose_name='Bulgular')),
                ('major_nc_count', models.PositiveIntegerField(default=0, verbose_name='Major NC')),
                ('minor_nc_count', models.PositiveIntegerField(default=0, verbose_name='Minor NC')),
                ('observations_count', models.PositiveIntegerField(default=0, verbose_name='Observation')),
                ('outcome', models.CharField(choices=[('PENDING', 'Beklemede'), ('PASSED', 'Uygun'), ('PASSED_FINDINGS', 'Uygun (bulgu ile)'), ('CONDITIONAL', 'Şartlı'), ('FAILED', 'Uygun değil')], default='PENDING', max_length=20, verbose_name='Sonuç')),
                ('corrective_action_deadline', models.DateField(blank=True, null=True, verbose_name='Düzeltici aksiyon son tarihi')),
                ('corrective_actions', models.TextField(blank=True, verbose_name='Düzeltici aksiyon planı')),
                ('report_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='Denetim raporu (PDF)')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Sertifika düzenlendi')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='Sonraki denetim')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notified_body', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chemicals.notifiedbody', verbose_name='Onaylanmış Kuruluş')),
            ],
            options={
                'verbose_name': 'historical FPC Audit',
                'verbose_name_plural': 'historical FPC Audits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
