# Generated by Django 5.1.15 on 2026-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('masterdata', '0002_product_business_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='attachment',
            field=models.TextField(blank=True, help_text='Orijinal fatura belgesi (PDF veya tarama). Maks 10 MB.', max_length=100, null=True, verbose_name='Fatura eki (PDF/JPG/PNG)'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='attachment_note',
            field=models.CharField(blank=True, help_text="Örn. 'Tedarikçi orijinali', 'DGI tebliğ dosyası'", max_length=200, verbose_name='Ek açıklaması'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, help_text='Orijinal fatura belgesi (PDF veya tarama). Maks 10 MB.', null=True, upload_to='invoices/%Y/%m/', verbose_name='Fatura eki (PDF/JPG/PNG)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='attachment_note',
            field=models.CharField(blank=True, help_text="Örn. 'Tedarikçi orijinali', 'DGI tebliğ dosyası'", max_length=200, verbose_name='Ek açıklaması'),
        ),
        migrations.AddField(
            model_name='payment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Havale dekontu, LC belgesi veya diğer ödeme evrakı.', null=True, upload_to='payments/%Y/%m/', verbose_name='Ödeme belgesi (PDF/JPG)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_bank',
            field=models.CharField(blank=True, choices=[('BEA', "BEA (Banque Extérieure d'Algérie)"), ('BNA', "BNA (Banque Nationale d'Algérie)"), ('CPA', "CPA (Crédit Populaire d'Algérie)"), ('BADR', "BADR (Banque de l'Agriculture)"), ('BDL', 'BDL (Banque de Développement Local)'), ('CNEP', 'CNEP-Banque'), ('AGB', 'AGB (Gulf Bank Algeria)'), ('SGA', 'SGA (Société Générale Algérie)'), ('BNP', 'BNP Paribas El Djazaïr'), ('FRB', 'Fransabank El Djazaïr'), ('TRUST', 'Trust Bank Algeria'), ('HOUSING', 'Housing Bank'), ('OTHER', 'Diğer / Other')], max_length=12, verbose_name='Çek bankası'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_bounce_reason',
            field=models.CharField(blank=True, help_text='check_status = BOUNCED olduğunda banka gerekçesi.', max_length=200, verbose_name='Karşılıksız gerekçesi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_drawer_name',
            field=models.CharField(blank=True, help_text='Çek üzerindeki keşideci adı (kişi veya şirket).', max_length=200, verbose_name='Çeki keşide eden'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_due_date',
            field=models.DateField(blank=True, help_text='Post-dated (ileri tarihli) çek için doldurulur.', null=True, verbose_name='Vade tarihi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_image',
            field=models.FileField(blank=True, null=True, upload_to='checks/%Y/%m/', verbose_name='Çek görseli (fotoğraf/tarama)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Keşide tarihi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_number',
            field=models.CharField(blank=True, help_text='Çek üzerindeki sıra numarası', max_length=40, verbose_name='Çek no'),
        ),
        migrations.AddField(
            model_name='payment',
            name='check_status',
            field=models.CharField(blank=True, choices=[('ISSUED', 'Kesildi (Émis)'), ('DEPOSITED', 'Bankaya yatırıldı (Déposé)'), ('CLEARED', 'Tahsil edildi (Encaissé)'), ('BOUNCED', 'Karşılıksız (Impayé)'), ('CANCELLED', 'İptal (Annulé)')], max_length=12, verbose_name='Çek durumu'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Havale / EFT (Virement)'), ('CHECK', 'Çek (Chèque)'), ('CASH', 'Nakit (Espèces)'), ('LC', 'Akreditif (Crédoc)'), ('CARD', 'Kart (Carte CIB)')], max_length=15, verbose_name='Yöntem'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'check_status'], name='accounting__method_41a51c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['check_due_date'], name='accounting__check_d_df7cb9_idx'),
        ),
    ]
