# Generated by Django 5.1.15 on 2026-08-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_historicalinvoice_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transfer_bank',
            field=models.CharField(blank=True, choices=[('BEA', "BEA (Banque Extérieure d'Algérie)"), ('BNA', "BNA (Banque Nationale d'Algérie)"), ('CPA', "CPA (Crédit Populaire d'Algérie)"), ('BADR', "BADR (Banque de l'Agriculture)"), ('BDL', 'BDL (Banque de Développement Local)'), ('CNEP', 'CNEP-Banque'), ('AGB', 'AGB (Gulf Bank Algeria)'), ('SGA', 'SGA (Société Générale Algérie)'), ('BNP', 'BNP Paribas El Djazaïr'), ('FRB', 'Fransabank El Djazaïr'), ('TRUST', 'Trust Bank Algeria'), ('HOUSING', 'Housing Bank'), ('OTHER', 'Diğer / Other')], help_text='Havalenin geldiği/gittiği banka.', max_length=12, verbose_name='Havale bankası'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_date',
            field=models.DateField(blank=True, help_text='Havalenin bankalar arası valörü.', null=True, verbose_name='Havale efektif tarihi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transfer_iban',
            field=models.CharField(blank=True, help_text="Karşı tarafın IBAN'ı veya hesap numarası.", max_length=40, verbose_name='IBAN / Hesap no'),
        ),
    ]
