# Generated by Django 5.1.15 on 2026-08-19 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_payment_transfer_bank_payment_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Satır HT toplamı üzerinden uygulanan iskonto yüzdesi.', max_digits=5, verbose_name='İskonto (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='İskonto tutarı'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Satır HT toplamı üzerinden uygulanan iskonto yüzdesi.', max_digits=5, verbose_name='İskonto (%)'),
        ),
    ]
