# Generated by Django 5.1.15 on 2026-08-21 08:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_historicalinvoice_discount_amount_and_more'),
        ('masterdata', '0004_sprint4_stock_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('advance_number', models.CharField(max_length=40, unique=True, verbose_name='Avans No')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar (TTC)')),
                ('currency', models.CharField(default='DZD', max_length=5, verbose_name='Para')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Havale / EFT'), ('CHECK', 'Çek'), ('CASH', 'Nakit')], default='BANK_TRANSFER', max_length=16, verbose_name='Yöntem')),
                ('reference', models.CharField(blank=True, help_text='Havale ref no / çek no / makbuz no.', max_length=120, verbose_name='Belge referansı')),
                ('status', models.CharField(choices=[('OPEN', 'Açık (kısmen/tamamen kullanılabilir)'), ('FULLY_ALLOCATED', 'Tam tahsis edildi'), ('REFUNDED', 'İade edildi'), ('CANCELLED', 'İptal')], default='OPEN', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='masterdata.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Avansı (§23)',
                'verbose_name_plural': 'Müşteri Avansları (§23)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerAdvance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('advance_number', models.CharField(db_index=True, max_length=40, verbose_name='Avans No')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar (TTC)')),
                ('currency', models.CharField(default='DZD', max_length=5, verbose_name='Para')),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Havale / EFT'), ('CHECK', 'Çek'), ('CASH', 'Nakit')], default='BANK_TRANSFER', max_length=16, verbose_name='Yöntem')),
                ('reference', models.CharField(blank=True, help_text='Havale ref no / çek no / makbuz no.', max_length=120, verbose_name='Belge referansı')),
                ('status', models.CharField(choices=[('OPEN', 'Açık (kısmen/tamamen kullanılabilir)'), ('FULLY_ALLOCATED', 'Tam tahsis edildi'), ('REFUNDED', 'İade edildi'), ('CANCELLED', 'İptal')], default='OPEN', max_length=16, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.customer', verbose_name='Müşteri')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Müşteri Avansı (§23)',
                'verbose_name_plural': 'historical Müşteri Avansları (§23)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tahsis edilen tutar')),
                ('date', models.DateField(verbose_name='Tahsis tarihi')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_allocations', to='accounting.invoice', verbose_name='Fatura')),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accounting.customeradvance', verbose_name='Avans')),
            ],
            options={
                'verbose_name': 'Avans Tahsisi (§23)',
                'verbose_name_plural': 'Avans Tahsisleri (§23)',
                'ordering': ['-date'],
                'unique_together': {('advance', 'invoice')},
            },
        ),
    ]
