# Generated by Django 5.1.15 on 2026-08-21 09:04

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_sprint5_advance'),
        ('masterdata', '0004_sprint4_stock_thresholds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('expense_number', models.CharField(max_length=40, unique=True, verbose_name='Fiche No')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Réparation / Maintenance'), ('UTILITY', 'Elektrik / Su / Doğalgaz'), ('RENT', 'Kira'), ('CONSULTING', 'Danışmanlık / Etüd'), ('TRANSPORT', 'Nakliye / Yakıt'), ('CLEANING', 'Temizlik / Hijyen'), ('SECURITY', 'Güvenlik'), ('OFFICE', 'Ofis / Kırtasiye'), ('LEGAL', 'Hukuk / Vergi'), ('MARKETING', 'Pazarlama / Reklam'), ('OTHER', 'Autre / Diğer')], max_length=20, verbose_name='Catégorie')),
                ('invoice_date', models.DateField(verbose_name='Fatura tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade tarihi')),
                ('description', models.TextField(help_text='Récapitulatif des travaux effectués — gider konusu.', verbose_name='Détails / Açıklama')),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=80, verbose_name='Facture n° du fournisseur')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant HT')),
                ('amount_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant TTC')),
                ('amount_in_words', models.CharField(blank=True, help_text='Cezayir yasal gereklilik: tutarın harfle yazılışı.', max_length=300, verbose_name='Arrivée en toutes lettres')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SUBMITTED', 'Onaya sunuldu'), ('APPROVED', 'Onaylandı'), ('PAID', 'Ödendi'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Statut')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='expense_invoices/%Y/%m/', verbose_name='Facture (PDF/JPG/PNG)')),
                ('equipment_reference', models.CharField(blank=True, help_text='Ör. Reactor R-101, Klima Ofis 2, vs.', max_length=200, verbose_name='Ekipman / Yer referansı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='Ödeme referansı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Giriş yapan')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_invoices', to='accounting.period', verbose_name='Dönem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_invoices', to='masterdata.supplier', verbose_name='Fournisseur')),
                ('tva_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_invoices', to='accounting.tvarate', verbose_name='TVA')),
            ],
            options={
                'verbose_name': 'Facture de Dépense',
                'verbose_name_plural': 'Factures de Dépense',
                'ordering': ['-invoice_date', '-expense_number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalExpenseInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Güncellenme')),
                ('expense_number', models.CharField(db_index=True, max_length=40, verbose_name='Fiche No')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Réparation / Maintenance'), ('UTILITY', 'Elektrik / Su / Doğalgaz'), ('RENT', 'Kira'), ('CONSULTING', 'Danışmanlık / Etüd'), ('TRANSPORT', 'Nakliye / Yakıt'), ('CLEANING', 'Temizlik / Hijyen'), ('SECURITY', 'Güvenlik'), ('OFFICE', 'Ofis / Kırtasiye'), ('LEGAL', 'Hukuk / Vergi'), ('MARKETING', 'Pazarlama / Reklam'), ('OTHER', 'Autre / Diğer')], max_length=20, verbose_name='Catégorie')),
                ('invoice_date', models.DateField(verbose_name='Fatura tarihi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade tarihi')),
                ('description', models.TextField(help_text='Récapitulatif des travaux effectués — gider konusu.', verbose_name='Détails / Açıklama')),
                ('supplier_invoice_number', models.CharField(blank=True, max_length=80, verbose_name='Facture n° du fournisseur')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant HT')),
                ('amount_tva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant TVA')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant TTC')),
                ('amount_in_words', models.CharField(blank=True, help_text='Cezayir yasal gereklilik: tutarın harfle yazılışı.', max_length=300, verbose_name='Arrivée en toutes lettres')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SUBMITTED', 'Onaya sunuldu'), ('APPROVED', 'Onaylandı'), ('PAID', 'Ödendi'), ('REJECTED', 'Reddedildi'), ('CANCELLED', 'İptal')], default='DRAFT', max_length=12, verbose_name='Statut')),
                ('proof_document', models.TextField(blank=True, max_length=100, null=True, verbose_name='Facture (PDF/JPG/PNG)')),
                ('equipment_reference', models.CharField(blank=True, help_text='Ör. Reactor R-101, Klima Ofis 2, vs.', max_length=200, verbose_name='Ekipman / Yer referansı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay zamanı')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='Ödeme referansı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Giriş yapan')),
                ('period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.period', verbose_name='Dönem')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.supplier', verbose_name='Fournisseur')),
                ('tva_rate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.tvarate', verbose_name='TVA')),
            ],
            options={
                'verbose_name': 'historical Facture de Dépense',
                'verbose_name_plural': 'historical Factures de Dépense',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
