# Generated by Django 5.1.15 on 2026-08-10 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_historicalrawmateriallot'),
        ('production', '0002_historicalmaterialconsumption_and_more'),
        ('quality', '0002_historicalcertificateofanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('protocol', models.CharField(choices=[('MOCK', 'Mock (test)'), ('REST', 'REST API (JSON)'), ('FILE', 'Dosya (CSV/XML)'), ('HL7', 'HL7 (klinik)')], default='MOCK', max_length=8, verbose_name='Protokol')),
                ('endpoint_url', models.CharField(blank=True, help_text='REST için tam URL, dosya için dizin yolu', max_length=255, verbose_name='Endpoint URL')),
                ('credentials_env', models.CharField(blank=True, help_text='user:password ya da API key env değişkeni', max_length=80, verbose_name='Kimlik env anahtarı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'LIMS Endpoint',
                'verbose_name_plural': "LIMS Endpoint'ler",
            },
        ),
        migrations.CreateModel(
            name='LimsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('direction', models.CharField(choices=[('PUSH', 'Push (ERP → LIMS)'), ('PULL', 'Pull (LIMS → ERP)')], max_length=6, verbose_name='Yön')),
                ('status', models.CharField(choices=[('SUCCESS', 'Başarılı'), ('FAILED', 'Hatalı'), ('PARTIAL', 'Kısmi')], max_length=8, verbose_name='Durum')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='Çalıştırma')),
                ('records_processed', models.PositiveIntegerField(default=0, verbose_name='İşlenen kayıt sayısı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata mesajı')),
                ('payload_summary', models.TextField(blank=True, verbose_name='Özet')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='lims.limsendpoint', verbose_name='Endpoint')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_syncs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'LIMS Sync Log',
                'verbose_name_plural': 'LIMS Sync Logları',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('request_number', models.CharField(max_length=40, unique=True, verbose_name='Talep no')),
                ('priority', models.CharField(default='NORMAL', help_text='LOW / NORMAL / HIGH / URGENT', max_length=10, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('SENT', 'Gönderildi'), ('RECEIVED', 'Sonuç alındı'), ('FAILED', 'Hata')], default='PENDING', max_length=10, verbose_name='Durum')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim zamanı')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonuç alım zamanı')),
                ('lims_reference', models.CharField(blank=True, help_text="LIMS'in atadığı iç ID.", max_length=80, verbose_name='LIMS referansı')),
                ('payload_sent', models.JSONField(blank=True, default=dict, verbose_name='Gönderilen payload')),
                ('payload_received', models.JSONField(blank=True, default=dict, verbose_name='Alınan sonuç')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_requests', to='production.productionbatch', verbose_name='Parti')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='lims.limsendpoint', verbose_name='Endpoint')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lims_requests', to='inventory.rawmateriallot', verbose_name='Lot')),
                ('parameters', models.ManyToManyField(related_name='lims_requests', to='quality.qcparameter', verbose_name='Talep edilen parametreler')),
            ],
            options={
                'verbose_name': 'Örnek İstek (LIMS)',
                'verbose_name_plural': 'Örnek İstekler (LIMS)',
                'ordering': ['-created_at'],
            },
        ),
    ]
