# Generated by Django 5.1.15 on 2026-08-16 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('rule_no', models.PositiveSmallIntegerField(choices=[(1, 'R01'), (2, 'R02'), (3, 'R03'), (4, 'R04'), (5, 'R05'), (6, 'R06'), (7, 'R07'), (8, 'R08'), (9, 'R09'), (10, 'R10'), (11, 'R11'), (12, 'R12')], verbose_name='Kural no')),
                ('rule_title', models.CharField(max_length=200, verbose_name='Kural başlığı')),
                ('target_model', models.CharField(help_text='Örn. production.ProductionBatch', max_length=100, verbose_name='Hedef model')),
                ('target_pk', models.CharField(blank=True, help_text='Kaydedilmemiş nesne için boş olabilir.', max_length=100, verbose_name='Hedef PK')),
                ('target_repr', models.CharField(blank=True, max_length=200, verbose_name='Hedef görüntü')),
                ('attempted_action', models.CharField(choices=[('save', 'Kaydetme'), ('delete', 'Silme'), ('release', 'Serbest bırakma'), ('close', 'Kapatma'), ('consume', 'Tüketim'), ('ship', 'Sevkiyat'), ('other', 'Diğer')], default='save', max_length=16, verbose_name='Denenen aksiyon')),
                ('reason', models.TextField(help_text='Kural tetiklenme detayı — hangi alan, hangi değer.', verbose_name='İhlal nedeni')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Önceki/denenen değerler, ilişki referansları.', verbose_name='Ek bağlam')),
                ('blocked', models.BooleanField(default=True, help_text="True = kayıt engellendi (ValidationError). False = uyarı log'u.", verbose_name='Bloklandı mı?')),
                ('resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Çözüm notu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_violations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı (bilinen)')),
            ],
            options={
                'verbose_name': 'Kural İhlali',
                'verbose_name_plural': 'Kural İhlalleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rule_no', '-created_at'], name='rules_rulev_rule_no_c6e52b_idx'), models.Index(fields=['blocked', 'resolved'], name='rules_rulev_blocked_54f526_idx'), models.Index(fields=['target_model'], name='rules_rulev_target__838851_idx')],
            },
        ),
    ]
