# Generated by Django 5.1.15 on 2026-08-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalSampleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('ref', models.CharField(max_length=100, verbose_name='Ref')),
                ('resolved_type', models.CharField(blank=True, max_length=30, verbose_name='Çözülen tür')),
                ('result', models.CharField(choices=[('PASS', 'PASS (SLA içi)'), ('SLOW', 'SLOW (SLA ihlali)'), ('NOT_FOUND', 'NOT FOUND'), ('ERROR', 'ERROR')], max_length=10, verbose_name='Sonuç')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='Süre (ms)')),
                ('error_note', models.TextField(blank=True, verbose_name='Hata / not')),
                ('sampled_at', models.DateTimeField(auto_now_add=True, verbose_name='Örneklem zamanı')),
            ],
            options={
                'verbose_name': 'Retrieval Örneklem Raporu',
                'verbose_name_plural': 'Retrieval Örneklem Raporları',
                'ordering': ['-sampled_at'],
                'indexes': [models.Index(fields=['result'], name='api_retriev_result_fc3767_idx'), models.Index(fields=['-sampled_at'], name='api_retriev_sampled_9b2c3a_idx')],
            },
        ),
    ]
